### ISSUE TITLE
'Api' object has no attribute '_Api__auth'

### ISSUE THREAD

**Issue by philsturgeon** [bear/python-twitter#119]
Not sure why, when or how this started happening, but if I just do `self.twitter = twitter.Api()` my code has a bad time:

```
  File "/var/cron/stats/reach.py", line 30, in __init__
    self.twitter = twitter.Api()
  File "/usr/local/lib/python2.7/dist-packages/twitter.py", line 2350, in __init__
    self.SetCredentials(consumer_key, consumer_secret, access_token_key, access_token_secret)
  File "/usr/local/lib/python2.7/dist-packages/twitter.py", line 2382, in SetCredentials
    self._config = self.GetHelpConfiguration()
  File "/usr/local/lib/python2.7/dist-packages/twitter.py", line 2386, in GetHelpConfiguration
    json = self._RequestUrl(url, 'GET')
  File "/usr/local/lib/python2.7/dist-packages/twitter.py", line 4974, in _RequestUrl
    auth=self.__auth,
AttributeError: 'Api' object has no attribute '_Api__auth'
```

But if I use twitter.Api with named params then it's all good:

            api = twitter.Api(
                consumer_key=self.config['twitter']['consumer_key'],
                consumer_secret=self.config['twitter']['consumer_secret'],
                access_token_key=post['oauth_token'],
                access_token_secret=post['oauth_token_secret']
            )

The first example was taken from your readme, so it should work.

Ideas?

**Comment by uayyappa** [comment]
i found solution to this problem in following site


[http://himanen.info/solved-attributeerror-module-object-has-no-attribute-api/][1]

There are two Python libraries conflicting: twitter library and python-twitter library. The solution was quite straightforward:

    pip uninstall twitter

Then I just made it sure that python-twitter was certainly installed:

    pip install python-twitter

Thank you himanen it worked for me

**Comment by bear** [comment]
Thanks for updating the group with your solution!

On Tue, Jul 7, 2015 at 2:00 AM, u.v.n.r.ayyappaswamy <
notifications@github.com> wrote:

> i found solution to this problem in following site
>
> [
> http://himanen.info/solved-attributeerror-module-object-has-no-attribute-api/][1
> ]
>
> There are two Python libraries conflicting: twitter library and
> python-twitter library. The solution was quite straightforward:
>
> pip uninstall twitter
>
> Then I just made it sure that python-twitter was certainly installed:
>
> pip install python-twitter
>
> Thank you himanen it worked for me
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bear/python-twitter/issues/119#issuecomment-119081983>
> .
>



-- 
Bear

bear@andyet.com (email)
bear42@gmail.com (email)
bear@bear.im (xmpp, email)
http://bear.im

PGP Fingerprint = 9996 719F 973D B11B E111  D770 9331 E822 40B3 CD29
