### ISSUE TITLE
Installation error with python 3.4.0

### ISSUE THREAD

**Issue by foxmask** [bear/python-twitter#155]
```python
byte-compiling build/bdist.linux-x86_64/egg/twitter/_file_cache.py to _file_cache.cpython-34.pyc
  File "build/bdist.linux-x86_64/egg/twitter/_file_cache.py", line 65
    except (AttributeError, IOError, OSError), e:
                                             ^
SyntaxError: invalid syntax

byte-compiling build/bdist.linux-x86_64/egg/twitter/api.py to api.cpython-34.pyc
  File "build/bdist.linux-x86_64/egg/twitter/api.py", line 770
    print 'request_url', request_url, parameters
                      ^
SyntaxError: invalid syntax

byte-compiling build/bdist.linux-x86_64/egg/twitter/__init__.py to __init__.cpython-34.pyc
  File "build/bdist.linux-x86_64/egg/twitter/__init__.py", line 36
    raise ImportError, "Unable to load a json library"
                     ^
SyntaxError: invalid syntax

byte-compiling build/bdist.linux-x86_64/egg/twitter/list.py to list.cpython-34.pyc
```

for the first error we should have 

```python
    except (AttributeError, IOError, OSError) as e:
```
this instruction is not python 2.5 compatible ( http://stackoverflow.com/questions/2535760/python-try-except-comma-vs-as-in-except )

for the seconde we should have 

```python
    print ('request_url', request_url, parameters)
```
to keep compatibility with python < 3 you could use 

```python
from __future__ import (print_function)
```

for the last it should be 

```python
    raise ImportError("Unable to load a json library")
```

**Comment by timabbott** [comment]
I'm curious if there's any update on Python 3 support for this library since it's one of the blockers for Zulip supporting Python 3 (https://github.com/zulip/zulip/issues/256)

**Comment by bear** [comment]
let me bump this up on my project todo list and take a look

On Wed, Nov 4, 2015 at 12:44 AM, Tim Abbott <notifications@github.com>
wrote:

> I'm curious if there's any update on Python 3 support for this library
> since it's one of the blockers for Zulip supporting Python 3 (
> zulip/zulip#256 <https://github.com/zulip/zulip/issues/256>)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bear/python-twitter/issues/155#issuecomment-153583897>
> .
>



-- 
Bear

bear42@gmail.com (email)
bear@bear.im (xmpp, email)
http://bear.im

PGP Fingerprint = 9996 719F 973D B11B E111  D770 9331 E822 40B3 CD29

**Comment by bear** [comment]
@timabbott I just merged all of the work that was in master into the python-v3 branch, would you mind giving the branch a run with Zulip as a sanity check?

**Comment by timabbott** [comment]
Cool yeah can take a look when I get a chance!


        -Tim Abbott

**Comment by bear** [comment]
K, I have just made the python-v3 branch test cleanly using v3.5 *and* I have also wrapped all of the v3 goodness in try blocks so it works properly when run under v2.7

I'm now definitely looking for folks to kick the tires on this so we can get this merged.

**Comment by bear** [comment]
any reason for us to not merge this? I've tweaked a couple of things and added back 3.5 to travis.yml and it's running clean.

**Comment by timabbott** [comment]
Cool, thanks @bear!  Sorry I haven't had time to test with Zulip yet; my attention has been on other aspects of Zulip than Python 3 support.

**Comment by bear** [comment]
NP - projects often dictate their own schedule no matter how much we think we have control :)
