### ISSUE TITLE
Calling GetSleepTime earlier in loops

### ISSUE THREAD

**Issue by apassant** [bear/python-twitter#158]
`GetSleepTime` is used in many `GetX()` methods to avoid rate limiting

    while True:
        # Call the API and do stuff with the results
        # [...]
        sec = self.GetSleepTime('/API_URL')
        time.sleep(sec)

Yet, if the limit has been reached before and still not reseted, the first pass in the loop will raise a rate-limit error.

Wouldn't it be better to have this test at the beginning of the loop to make sure the exception is not raised?

    while True:
        sec = self.GetSleepTime('/API_URL')
        time.sleep(sec)
        # Call the API and do stuff with the results
        # [...]

**Comment by MikeHibbert** [comment]
I've already been doing this with my own custom versions that update celery task statuses and find its making live much easier so it has my vote!

**Comment by bear** [comment]
@apassant can you work up a PR for this with the suggest from @sebastianw included?

**Comment by apassant** [comment]
@bear will do - should be done by the end of next week

**Comment by anasb** [comment]
+1

**Comment by widian** [comment]
So, is there anyone who work to make an API option to sleep or raise an exception?

**Comment by bear** [comment]
@apassant did you get any time to work on this?

**Comment by apassant** [comment]
Sorry, still at the end of my backlog. I can prioritize that for next week
unless someone needs it ASAP and wants to go ahead before?

**Comment by widian** [comment]
I'm sorry but I already made a bypass for this issue. If there is another quite more important issue, please do more busy issue. I always thank you for this repository and contributors.

**Comment by bear** [comment]
@apassant no urgency, was just checking. From what @widian is saying a local work around is in place so this can be added at any time.

thanks to both of you for using and helping make python-twitter improve!

**Comment by jeremylow** [comment]
Closing with #299
