### ISSUE TITLE
Retrieving media entities

### ISSUE THREAD

**Issue by mih0001** [bear/python-twitter#16]
Should ensure that each function call that goes to Twitter has the ability to set the parameters to include_entities. 

For example, Get Mentions. I added include entities like shown: 

def GetMentions(self,
                  since_id=None,
                  max_id=None,
                  page=None,
                  include_entities=None):

More importantly, in line 616, 'urls' needs to be changed to 'media' to actually retrieve the data. Urls doesn't return data. See https://dev.twitter.com/docs/tweet-entities

Here is my new line 616 and 617

616      if 'media' in data['entities']:  ###changed 'urls' to 'media'
617                 urls = [Url.NewFromJsonDict(u) for u in data['entities']['media']]  #changed 'urls' to 'media'

**Comment by bear** [comment]
fixed in https://github.com/bear/python-twitter/pull/264
