### ISSUE TITLE
Expanding the URL Class

### ISSUE THREAD

**Issue by mih0001** [bear/python-twitter#17]
It would be nice to expand the class URL to include more data. Right now, it returns the 'url', but it would be nice to also get the 'media_url_https' and maybe a few other variables. URL only returns the twitter page, if you want to download the actual file, you will need media_url_https

You can see all of the options here under 'entities' 'media'

https://dev.twitter.com/docs/tweet-entities

**Comment by jeremylow** [comment]
Fixed in 3.1 (probably earlier though)
