### ISSUE TITLE
Add full API documentation to github

### ISSUE THREAD

**Issue by AmeliaMN** [bear/python-twitter#178]
I would much prefer to read the documentation on the web than by typing pydoc twitter.Api and scrolling through the whole thing. Text file, please?

**Comment by jeremylow** [comment]
I just added a new branch (https://github.com/bear/python-twitter/tree/feature/docs) since I was tracking changes locally with the 3.0 changes, which brings the documentation a little more up to date. Should work with readthedocs if you want to import the repository over there.

**Comment by nikolas** [comment]
I agree.. I can't figure out how to use pydoc in my virtualenv where i've installed python-twitter. `./venv/bin/pip install pydoc` doesn't work.. looking forward to seeing the documentation in sphinx/readthedocs.

**Comment by bear** [comment]
we are now on readthedocs:

http://python-twitter.readthedocs.org/en/latest/
