### ISSUE TITLE
tweet capturing is limiting to 10 to 15 tweets on the same code which was working very well some days ago

### ISSUE THREAD

**Issue by lovelydns** [bear/python-twitter#187]
I had written a code to capture tweets using my code (twython) which was working very well from long time but today when i was trying it is always stopping to capture tweets after 10 -15 tweets.

**Comment by jeremylow** [comment]
This happens a lot - twittercommunity.com is usually a good place for information about API weirdness if there have been no changes to python-twitter.

I'm going to close this issue since it's resolved.
