### ISSUE TITLE
Unit tests have (private) keys hardcoded i them.

### ISSUE THREAD

**Issue by maurodec** [bear/python-twitter#188]
The `ApiTest` class is the base of all unit tests, and in it's `setUp` method it creates an instance of the `Api` class for use in unit tests. However, when instantiating the class, it uses hardcoded keys as well as tokens. 

These keys and tokens should be:
* Constants, defined at the beginning of the class or module.
* Removed completely form the file since they are private,

The documentation should also be updated to provide information on how unit tests should be run.

**Comment by jonathan-s** [comment]
@bear This has been solved.

**Comment by bear** [comment]
thanks
