### ISSUE TITLE
get_access_token module is not included in PyPI packages

### ISSUE THREAD

**Issue by amorphic** [bear/python-twitter#192]
I'm not sure if I'm missing something, but the `get_access_token` module doesn't seem to be included in either the .tar.gz or .whl in the 2.0 release on PyPI.

A cursory glance at `setup.py` shows that modules are included using `find_packages()`, which won't include .py files in the root according to [this](https://pythonhosted.org/setuptools/setuptools.html#using-find-packages).

Without `get_access_token`, I'm unable to authenticate my application with Twitter.

**Comment by sid-kap** [comment]
Why can't we add it as an executable to the package, so it can be run by `get_access_token`? Or at least a runnable module, so someone can run `python -m twitter.get_access_token`?
