### ISSUE TITLE
How to update_profile_image ?

### ISSUE THREAD

**Issue by rajasimon** [bear/python-twitter#207]
I just want to `update_profile_image` but there's no such function in `api.py` file. So can you tell is it possible to update profile image to twitter

**Comment by jonathan-s** [comment]
@rajasimon It looks like that hasn't been implemented in twitter api wrapper yet. There is a way to do that though, as described here: https://dev.twitter.com/rest/reference/post/account/update_profile_image

**Comment by rajasimon** [comment]
Well... May be it's not documented but I did it. https://github.com/bear/python-twitter/pull/208

**Comment by jonathan-s** [comment]
Cool, I just saw this unanswered issue and thought I'd reply to it :)
