### ISSUE TITLE
ImportError: No module named '_file_cache'

### ISSUE THREAD

**Issue by tonydot28** [bear/python-twitter#209]
I am upgrading my project from Python 2 to 3. I get

ImportError: No module named '_file_cache'

Python 3.4.0, Django 1.7.2 Python-twitter 2.2

**Comment by radlws** [comment]
I don't believe there is python 3 support yet. It would be good for someone to start migrating the code slowly to use "futures" so in the end it would support both  Py 2 and 3.

**Comment by bear** [comment]
Their is a python 3 branch where I started exploring it, but yes, python v3 is not fully supported yet

**Comment by grcninja** [comment]
Bear, thanks for taking time to build this.  I'm still extremely new to python so please forgive me if my question or comment seems dumb, I'm a grasshopper learning from  you Sensei's :)

I have Python3.4 installed and I ran the setup.py and got what appeared to be some errors, would you like them emailed to you?  Also, I updated the print commands in the twitter_test.py to have parenthesis and double quotes, but then I got stuck on the same error as tonydot28.
  File "twitter_test.py", line 30, in <module>
    import twitter
  File "C:\Python34\Twitter-API-Wrapper\python-twitter-master\twitter\__init__.py", line 31, in <module>
    from _file_cache import _FileCache
ImportError: No module named '_file_cache'

I am all about learning and I gather that this probably has something to do with syntax, so if you'd be kind enough to impart your wisdom on me as how to fix it, I'll gladly go make the changes, just need a nudge in the right direction. :)

**Comment by bear** [comment]
currently the main branch of the code does not work with Python v3 - that is being worked on in the Python-v3 branch but it may have bugs.

I would suggest you start by getting the Python-v3 branch and seeing if it works better for you.

**Comment by grcninja** [comment]
Thanks Bear :) I also ran the 2to3 converter on the entire module and made an identical one just so I an learn :+1:  you are AWESOME!

**Comment by bear** [comment]
going to close this issue since the python-v3 branch now exists

**Comment by exhuma** [comment]
For anyone else coming across this: I just ran into this today and I had to install directly from the repo using:

    ./env/bin/pip install git+https://github.com/bear/python-twitter --upgrade

Any information on when this will officially be released?

**Comment by bear** [comment]
I was waiting for signs that someone was using it on v3 Python just to make sure it wasn't completely broken...

if you agree with the above then it sounds like we can merge the v3 branch and get a release started

**Comment by exhuma** [comment]
I have not made any exhaustive tests. I am currently trying to get twitter login working using flask-security + flask-social + python-twitter.

The current pip release of python-twitter does not work on 3. Installing it from the repo now makes the imports working, but now I've run into [a bug in flask-social](https://github.com/mattupstate/flask-social/issues/76). So, as I have no complete working solution yet, I cannot tell you if python-twitter is okay.

**Comment by bear** [comment]
that's ok - we do appreciate the report either way.

as a flask user myself I am curious about your integrations - please do file any issues for things that would make life easier

**Comment by exhuma** [comment]
It's looking good so far. The login process works. Do you have anything specific for me to check other than the login process?

I'm still mostly battling with flask-social. It's a fairly treacherous minefield ;) Once I've figured everything out, I'll start from scratch and see which issues I have are related to python-twitter. But from what I can tell right now, all of the issues are related to flask-social.

**Comment by bear** [comment]
The good thing about twitter (and python-twitter) is that once you can login and do at least one successful pull everything else normally works.

The exception is rate limiting

**Comment by jeremylow** [comment]
The @/properties in some of the objects don't work anymore. I'm working on that issue, which touches a couple others, but have not had the time to really put something coherent together. There's also the lack of mute support, but I don't know if that should block a significant release. I should have time this weekend to organize and put together a pull request.

Also, CHANGES references Collections, but I didn't see that in the code. It looks like the PR was closed without merging; not sure if that was intentional.

That said, I'm using the master branch for a project and have not had any issues (admittedly, a small archival project, so probably not generalizable).

**Comment by bear** [comment]
hmm, I really try to put only closed PRs into CHANGES but, to be honest with myself, I don't look at *why* a PR is closed :/

If you think it was in error, reopen and give me a poke :)

**Comment by fullmogra** [comment]
I am not able to import package twitter as I have python 3.5.
I am new to this environment. I have the code from Git.
Cloning into 'python-twitter'...
remote: Counting objects: 2579, done.
remote: Total 2579 (delta 0), reused 0 (delta 0), pack-reused 2579 eceiving objects:  98% (2528/2579), 2.15 MiB | 2.10 MiB/s
Receiving objects: 100% (2579/2579), 3.94 MiB | 2.10 MiB/s, done.
Resolving deltas: 100% (1613/1613), done.
Checking connectivity... done.
Checking out files: 100% (209/209), done.

how do i make it work ? please can you provide detail steps.
thanks

**Comment by jeremylow** [comment]
hey @fullmogra, can you open a new issue and include your operating system and the error that you're getting when you try to import the package?

**Comment by fullmogra** [comment]
Ok i will. Tweepy worked though. I would like to try your package though.
Thanks

--Aarti
