### ISSUE TITLE
Possible issue with getting favorites list, urls property

### ISSUE THREAD

**Issue by agerber23** [bear/python-twitter#215]
** solved **

**Comment by bear** [comment]
The GetFavorites() call returns a list of python-twitter Status objects so you will need to do something like:

for status in api.GetFavorites(screen_name="KingJames", count=10):
    print status.user.screen_name, status.id, status.text

you will only get a urls field when the returned twitter object contains it, so you should do a check for 'urls' in status before referencing it.

**Comment by agerber23** [comment]
right, if the urls field is present, it looks like this in the json:
"urls": {"http://t.co/s4FteNUpsw": "http://vevo.ly/smYyG6"}
however, I'm having trouble accessing it. when I do status.urls it won't print, or status.urls[0]. it prints out memory addresses, but the other fields work with the status.user etc.

Any tips on how to print out the urls when it does exist without printing the memory address like <twitter.url.Url object at 0x1085554...>

**Comment by bear** [comment]
yea, that's a side effect of how the library converts the json from twitter to the internal Status object - it's on our list to improve.

this is how I tested it just now:

        for o in api.GetFavorites(screen_name='codebear', include_entities=True):
            d = o.AsDict()
            if 'urls' in d:
                print o.user.screen_name
                for u in o.urls:
                    print u

What your seeing in o.urls is that it's a list of Url helper objects, so you have to dereference them.

The .AsDict() helper method is a great way to debug or get some data out of the layers of helper objects that the code has.
