### ISSUE TITLE
Missing module future import standard_library

### ISSUE THREAD

**Issue by grcninja** [bear/python-twitter#220]
Gents,

Since I have Python 3, I went and removed all the Python 2 code as you had suggested and I've pulled down python-twitter-python-v3 and have run the setup.  After successfully completing that, I ran the twitter_test.py and it is failing at line 23.  Thank you for your continued work on this project, it is greatly appreciated. 

from future import standard_library

**Comment by bear** [comment]
fixed with the merging of the python-v3 branch - pull request #251
