### ISSUE TITLE
default repl does not return work with unicode values in properties

### ISSUE THREAD

**Issue by rajasimon** [bear/python-twitter#228]
Just tried and gave me this error.. 

	(flask)tests-MBP:RealTimeHashtag simon$ python
	Python 2.7.6 (default, Sep  9 2014, 15:04:36) 
	[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)] on darwin
	Type "help", "copyright", "credits" or "license" for more information.
	>>> import twitter
	>>> from config import api
	>>> api.GetTrendsCurrent()
	/Users/simon/Nightybuild/flask/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
	  InsecurePlatformWarning
	[Traceback (most recent call last):
	  File "<stdin>", line 1, in <module>
	UnicodeEncodeError: 'ascii' codec can't encode characters in position 1-5: ordinal not in range(128)

**Comment by bear** [comment]
which version of python-twitter is this?

**Comment by rajasimon** [comment]
python-twitter==2.2

**Comment by bear** [comment]
any chance you can get the full trace? v2.2 should not have any problems with unicode

**Comment by rajasimon** [comment]
Ya but it's happening. No there is no full tracebook just this one. I installed with python-twitter==2.3 but problem still.

**Comment by jonathan-s** [comment]
You can get the full traceback if you run it from a file rather from the
console.

On Tuesday, April 28, 2015, Simon Rajasingh <notifications@github.com>
wrote:

> Ya but it's happening. No there is no full tracebook just this one. I
> installed with python-twitter==2.3 but problem still.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bear/python-twitter/issues/228#issuecomment-97160686>.
>


-- 
Sent from Gmail Mobile

**Comment by bear** [comment]
I just duplicated it - let me look

**Comment by bear** [comment]
The issue is Python v2.7 and it's default repl not working well with Unicode.

when you reference api.GetTrendsCurrent() you are receiving a list of Trend objects so it then tries to convert each one to a string. I only get that error when I do that.

but this works just fine:

        for trend in api.GetTrendsCurrent():
            pp.pprint(trend.name)
            pp.pprint(trend.query)
            pp.pprint(trend.timestamp)
            pp.pprint(trend.url)

it even works if you remove prettyprint and just do print...

I'm going to change this bug to be about us getting a proper repl function in place for each of the classes.

thanks
