### ISSUE TITLE
geocode search fail

### ISSUE THREAD

**Issue by bear** [bear/python-twitter#232]
Reported by Felix via the mailing list:

i installed from pip the twitter-python module found out that geocode searches didnt worked 

i did this modification to make it work - inside the api.py

searched for the GetSearch function in my file the function is located at line 265

  def GetSearch(self,
                term=None,
                geocode=None,
                since_id=None,
                max_id=None,
                until=None,
                count=15,
                lang=None,
                locale=None,
                result_type="mixed",
                include_entities=None):

inside the function it checks for parameters if are set, for geocode it checks like this 

    if geocode is not None:
      #parameters['geocode'] = ','.join(map(str, geocode))

this fancy stuff ','.join stuff doesnt worked as i expected because it turns the geocode data to be sent as a string of characters(strings ) something like ['-','3','0','.' ...] etc , looking at the api documentation i found the parameter geocode needs to be something like http://..../...&geocode=30.090923,45.0909,1m
so the solution is to set the parameter like twitter.Api.GetSearch(param="something", geocode="40.498823,90.9090,1mi")

inside the check  i just converted the parameter geocode to string like this

    if geocode is not None: <<--- line 348 api.py 
      parameters['geocode'] = str(geocode)
      #parameters['geocode'] = ','.join(map(str, geocode)) <<---- this doessnt work, comment/delete

**Comment by interneteur** [comment]
Thanks for this quick solution, spent a few hours trying to figure out what I was doing.  This bug should deff be forked and added

**Comment by jeremylow** [comment]
lands in #296
