### ISSUE TITLE
Arabic support?

### ISSUE THREAD

**Issue by qasimalbaqali** [bear/python-twitter#234]
While extracting tweet text and hashtags I can't get it to extract them in Arabic instead I get a mumble jumble text i.e "#\u0643\u0631\u0628\u0627\u0628\u0627\u062f". Any way to make this work to print out Arabic text instead?

**Comment by bear** [comment]
Can you show me a small snippet of code as an example? 

My hunch is that you need to add a .decode("utf-8") to the twitter result

**Comment by philshem** [comment]
Decoding gives me this: #كرباباد
http://rishida.net/tools/conversion/

**Comment by bear** [comment]
So the decode worked then - I can add that to the code so it's always returned as utf-8
