### ISSUE TITLE
Add user parameter to GetFollowers()

### ISSUE THREAD

**Issue by jsuzack** [bear/python-twitter#238]
I noticed on the old Google project a few folks expanded api.GetFollowers() to take a user parameter similar to GetFriends(). Does anyone have a suggestion for implementing this and adding it to the repo?

Old Issue Listing: https://code.google.com/p/python-twitter/issues/detail?id=47

**Comment by era** [comment]
Hello :), I think this was already implemented here: https://github.com/bear/python-twitter/blob/master/twitter/api.py#L1715.

**Comment by bear** [comment]
@era thanks for the update 

it sure does look like it's been solved and we should close this issue!
