### ISSUE TITLE
api.GetUserByEmail(...) does not exist

### ISSUE THREAD

**Issue by tedmiston** [bear/python-twitter#240]
This call is mentioned in a docstring and in the html docs, but doesn't seem to be defined anywhere.  I wasn't able to find it in the Twitter API docs either.  Is it a lingering relic of an old API version?

https://github.com/bear/python-twitter/blob/0a0dbd612d9e6d36e55fe5dc71b10b06b2e6ea96/twitter/api.py#L103

https://github.com/bear/python-twitter/blob/91a38d2de5c58cb12fe6ccf37b4053a03b0d0608/doc/twitter.html#L751

**Comment by bear** [comment]
yes, a lot of references to email were removed from the API a while ago, another item on the list of why docs need refreshing :/

**Comment by tedmiston** [comment]
I see.  Would you rather get small PRs to whittle down the outdated pieces one-by-one, or a big request that updates all of the docstrings?

**Comment by bear** [comment]
I leave those decisions up to you - if your doing the work i'm not going to quibble over how ;)
