### ISSUE TITLE
Data obtained from API to json

### ISSUE THREAD

**Issue by fdevillalobos** [bear/python-twitter#247]
Hey guys,

Just a question... Maybe I'm doing something wrong but I can't seem to get the user data into a json format even with the AsJsonString method.

```
user = api.GetUser( 1234 )
user_json = json.loads( user.AsJsonString )
print( user_json['followers_count'] )
```

Why is this not working?? (It errors out on AsJsonString telling me that TypeError: expected string or buffer). How can I get access to the individual fields of the user without this method??
Thanks a lot.
Francisco.

**Comment by bear** [comment]
AsJsonString should always be convertable back to a dictionary because that is how it's created, so yea I'm wondering what is up. What version are you using?

Also, you can always get to the individual items either as the property of the user object:

  user.followers_count 

or you can use .AsDict() and then reference it as a key:

    user.AsDict()['followers_count']

**Comment by fdevillalobos** [comment]
I'm using:

```
pip show python-twitter
---
Metadata-Version: 2.0
Name: python-twitter
Version: 2.2
Summary: A Python wrapper around the Twitter API
Home-page: https://github.com/bear/python-twitter
Author: The Python-Twitter Developers
Author-email: python-twitter@googlegroups.com
License: Apache License 2.0
Location: /usr/local/lib/python2.7/site-packages
Requires: requests, requests-oauthlib
```

I don't know if it's weird or what. Yeah... I knew about doing user.follower_count and I ended up doing this. But I was trying to stream straight json out. No worries, just wondering what was it that I was doing wrong. Will also try the AsDict methon then.

**Comment by bear** [comment]
It is still bothering me that what you have didn't work - so I'm going to leave this open until I get a chance to reproduce it

**Comment by jeremylow** [comment]
@fdevillalobos if that's the code you are using verbatim, the problem is that the AsJsonString is a method, not a property of the User object. The code you want is:

    user = api.GetUser( 1234 )
    user_json = json.loads( user.AsJsonString() )
    print( user_json['followers_count'] )

**Comment by jeremylow** [comment]
Hey folks, can this issue be closed? I'm trying to clean out some of the older ones.

**Comment by chuckoy** [comment]
Yeah seems to have been resolved.
