### ISSUE TITLE
Fastest way to download last image of a twitter account

### ISSUE THREAD

**Issue by davboc** [bear/python-twitter#263]
Hi!
I have two questions for you:
What is the fastest way to download last image of a twitter account?
There is a way to download only an image from a twitter account where, in the tweet, is present a particular hashtag?

Thank you everybody.

**Comment by RobinStephenson** [comment]
@davboc 
By the last image do you mean the most recently posted?
As for your second question this is possible. You can do a [GET statuses/user_timeline](https://dev.twitter.com/rest/reference/get/statuses/user_timeline) (or however you are looking for tweets). Any tweets you get that way (or any other way) with images will contain [entities](https://dev.twitter.com/overview/api/entities-in-twitter-objects#media) which you can use to get a link for the media. Simply use a regex or just search the tweet for the hashtag you want and then download the media from the entity.
