### ISSUE TITLE
URL shortening woes

### ISSUE THREAD

**Issue by dper** [bear/python-twitter#265]
I'm using `python-twitter` to try to post a message like this.

> Let's try again with a message including the URL that was causing chaos two weeks ago. In other words: strugee.net is the second test.

The message as-is is under 140 characters, but Twitter "shortens" the URL (strugee.net) to something longer. That hits the 140 character limit and I get an error message.

```
{u'message': u'Status is over 140 characters.', u'code': 186}
```

My first attempt at posting was using `api.PostUpdate`.  My second attempt was using `api.PostUpdates`.  They both produced the same error.  I was hoping that `PostUpdates` would recognize what was happening and split the message into two.

See the downstream error at https://github.com/dper/pumptweet/issues/28

**Comment by dper** [comment]
Thanks!

**Comment by bear** [comment]
your very welcome!
