### ISSUE TITLE
`GetFriends()` `count` and `cursor` don't do anything useful

### ISSUE THREAD

**Issue by rbpasker** [bear/python-twitter#274]
One would imagine that if `count=20`, then no more than 20 items would be returned, but the way it is implemented, 20 items are returned **per page**, and the pages are concatenated to create a result. It will not keep you from getting rate limited at all. I guess since that's the way its documented it makes sense, but I just don't know what the purpose of 'count' is, since the caller doesn't get an updated value for 'cursor', which would allow the caller to do his own paging.

**Comment by bear** [comment]
yea, a lot of this really needs a refactoring since all of twitter's api have moved to a cursor model with the count parameter being optional and all

**Comment by rbpasker** [comment]
i'm going to close this based on https://github.com/bear/python-twitter/pull/275
