### ISSUE TITLE
Inconsistent Api.__auth checks

### ISSUE THREAD

**Issue by jeremylow** [bear/python-twitter#276]
The twitter.Api's methods don't reliably check if the Api is authorized (i.e., `Api.__auth is not None`). (20 methods do, 33 don't.) Since the Api checks to make sure that you can't instantiate it with a `consumer_key` but not access tokens/secrets:

        if consumer_key is not None and (access_token_key is None or
                                         access_token_secret is None):

a more consistent way to ensure that you're not trying to make unauthorized calls, would be to move the check:

        if not self.__auth:
            raise TwitterError({'message': "API must be authenticated."})

to `_RequestUrl()`, since all calls require authorization at this point. This would have the benefit of removing some duplicate code and increasing the reliability of the check.

**Comment by bear** [comment]
+1 - this reduces the surface area for false positives IMO

**Comment by jeremylow** [comment]
Closing with commit 071b09068a49732c6e8714c842088293d31224ac
