### ISSUE TITLE
Inconsistency between docstring & code for GetFriendsPaged() & GetFollowersPaged()

### ISSUE THREAD

**Issue by jeremylow** [bear/python-twitter#277]
Working through #275 , the doc strings for `GetFriendsPaged()` and `GetFollowersPaged()` states:

    Returns:
        cursor, previous_cursor, data sequence of twitter.User
        instances, one for each follower

But the method returns a dict containing the json data from the API. My inclination is that the doc string is correct, which also simplifies the GetFriends() and GetFollowers() methods (not having to convert to twitter.User objects on each pass of the while loop - you'd append the twitter.User objects and be done with it).

Any thoughts?

**Comment by bear** [comment]
+1 to following the doc string - each friend/follower is a distinct twitter user so having a sequence of twitter.User objects feels right
