### ISSUE TITLE
Api.GetSearch() parameters

### ISSUE THREAD

**Issue by jeremylow** [bear/python-twitter#280]
Currently, if you want to specify a couple different params to Twitter's search functionality, python-twitter's support for this is a little wonky. For example, getting `term='python'` from `who='@twitterapi'` doesn't really work since the `term` param gets overridden by the `who` param as follows:

    391:    if term is not None:
    392:        parameters['q'] = term
    393:
    394:    if who is not None:
    395:        parameters['q'] = "from:%s" % (who)

There are a couple other situations where I think this could be improved. Documentation from Twitter is here: https://dev.twitter.com/rest/reference/get/search/tweets . I wonder if a `raw_query` parameter might make sense? Implementing all of the documented options seems complicated, but maybe not.

**Comment by bear** [comment]
adding 'raw_query' and have it override everything works for me - trying to keep the implementation in sync with twitter is a tail-chasing excercise

**Comment by alexk307** [comment]
@jeremylow @bear Is this being worked on?

**Comment by jeremylow** [comment]
It's on my list if the crumbling infrastructure of the east coast has power
this weekend :)

**Comment by bear** [comment]
yea, i've been distracted with snow related issues for the last couple of days myself! stay warm and safe @jeremylow !

**Comment by jeremylow** [comment]
Thanks @bear , you too!

**Comment by jeremylow** [comment]
Closing with ded76f15b4b8b1f7f6791edb2d62b88299d77c30
