### ISSUE TITLE
xAuth

### ISSUE THREAD

**Issue by jimpresley63** [bear/python-twitter#292]
Any plans to include support for xAuth?

**Comment by bear** [comment]
you should be able to do that now - xAuth is only the part up to getting the access token and secret. 

I should probably create an example get_access_token.py that does the POST for xAuth.

**Comment by jimpresley63** [comment]
@bear Ahh...I think I'm tracking you. I did find an example gist (https://gist.github.com/codingjester/3497868) that illustrates xAuth with Tumblr that might help.

**Comment by bear** [comment]
yes, that is doing the xAuth token dance similar to what get_access_token.py does for oAuth - good find!

**Comment by andypiper** [comment]
xAuth was [retired](https://twittercommunity.com/t/retirement-of-xauth/88022) in June 2017.

**Comment by jeremylow** [comment]
Overtaken by events then, as they say
