### ISSUE TITLE
Unable to post a status update due to: 'Only unicode objects are escapable. Got <generator object <genexpr> at 0xb661bbe4> of type <type 'generator'>.'

### ISSUE THREAD

**Issue by Murtaza0xFF** [bear/python-twitter#293]
I'm trying to post a status update like so:

`s = api.PostUpdate('Test')
`

But I get the following error:

>Only unicode objects are escapable. Got generator object genexpr at 0xb661bbe4 of type type 'generator'.

**Comment by bear** [comment]
which version are you using?

**Comment by Murtaza0xFF** [comment]
Okay, I've got around it. I was separating the tokens and consumer keys with commas, which was causing this to happen.

**Comment by ScarletMcLearn** [comment]
XD I did the same thing

**Comment by bgoldfarb** [comment]
Lol I did the same thing......left it as an object

**Comment by percygautam** [comment]
i did the same tooo lol

**Comment by Laughing-Boy** [comment]
I am getting same error, Which comma do we remove?

**Comment by abner19** [comment]
Hello, can someone provide an example of which commas to remove.. thanks

**Comment by jeremylow** [comment]
If you follow [the example here](https://github.com/bear/python-twitter/blob/master/examples/view_friends.py), you should be good to go.

**Comment by Daksh** [comment]
In my case I had accidentally put a comma at the end, like `access_token = "25...",` right after the string's closing `"`

**Comment by sharmakamal1201** [comment]
lol I did the same mistake...

CONSUMER_KEY = 'XXXXXXXXXXXXXXXXXXXXXXX'
CONSUMER_SECRET = 'XXXXXXXXXXXXXXXXXXXXXXX'
OAUTH_TOKEN = 'XXXXXXXXXXXXXXXXXXXXXXX'
OAUTH_TOKEN_SECRET = 'XXXXXXXXXXXXXXXXXXXXXXX'

auth = tweepy.OAuthHandler(CONSUMER_KEY, CONSUMER_SECRET)
auth.set_access_token(OAUTH_TOKEN, OAUTH_TOKEN_SECRET)


I placed ',' at the end of each key

**Comment by TechniCollins** [comment]
Mine was a silly mistake. I was trying to get my API keys from an environment file but I had not added the keys to the file.

**Comment by ansev-0** [comment]
I think the error comes from thinking that we must enter our credentials in a python list like here : https://python-twitter.readthedocs.io/en/latest/getting_started.html , we simply have to pass the string as mentioned in other answers
