### ISSUE TITLE
switch to CircleCI for hook testing

### ISSUE THREAD

**Issue by bear** [bear/python-twitter#305]
My day-job is with CircleCI and I would like to use python-twitter to test CircleCI's python environment usage.

Anyone have any concerns about me switching from Travis to Circle?

@jeremylow ?

**Comment by jeremylow** [comment]
I was kind of wondering why ya hadn't already... :)

**Comment by bear** [comment]
others were the ones who added it to travis so unless I had a compelling reason I was going to leave it be :)

**Comment by bear** [comment]
implemented with pr #308
