### ISSUE TITLE
Is there any api to get all retweets of the specific tweet?

### ISSUE THREAD

**Issue by chealsea** [bear/python-twitter#306]

**Comment by bear** [comment]
the twitter API call is documented at https://dev.twitter.com/rest/reference/get/statuses/retweets/:id

and we implement it at https://github.com/bear/python-twitter/blob/master/twitter/api.py#L1503

**Comment by chealsea** [comment]
If the number of retweets is above 1000, how to get all retweets?

**Comment by bear** [comment]
The docs for statuses/retweets on the twitter dev page list https://dev.twitter.com/rest/reference/get/statuses/retweeters/ids as another one and it provides a cursor parameter so you can walk the entire history of it

**Comment by chealsea** [comment]
Do python-twitter have the parameter cursor? I didn't find it.

**Comment by jeremylow** [comment]
Additionally, there's a problem with Twitter's documentation or API. Here's a summary of the problem:

https://gist.github.com/jeremylow/3e4d6b0a18370f7444bb84ccdc136f2d

and the same thing on twittercommunity.com

https://twittercommunity.com/t/paging-is-not-possible-with-statuses-retweeters-ids-json/71298

When they update their behavior, python-twitter should start working for this endpoint without changes.

**Comment by brajeshjee** [comment]
Can anyone help to get all the lists of Retweets. I am getting only recent 20 with the below code.

retweets = twitter.statuses.retweets._id(_id = id)

**Comment by jeremylow** [comment]
There's no way to do so now unless you're paying for the commercial API, which we don't support. Sorry about that.
