### ISSUE TITLE
Documentation: where is it?

### ISSUE THREAD

**Issue by tmontanaro** [bear/python-twitter#311]
If I click on the documentation provided link ([https://python-twitter.readthedocs.org](url)) I get the following message: `You've found something that doesn't exist.`

**Comment by ojas1** [comment]
And the same incorrect link has been mentioned everywhere in the README.

**Comment by jeremylow** [comment]
@bear can you import the repo to readthedocs? I think I can do so manually, but I don't want to overstep.

**Comment by bear** [comment]
done - @jeremylow do you have a ReadTheDocs userid? I'll add you as a maintainer

**Comment by jeremylow** [comment]
Yep, it's jcbl. Thanks!

**Comment by bear** [comment]
@jeremylow ok, you have been added as a maintainer
