### ISSUE TITLE
Finalizing v3

### ISSUE THREAD

**Issue by jeremylow** [bear/python-twitter#315]
I think all of my issues have been taken care of; does anyone else have anything?

**Comment by bear** [comment]
I do not

**Comment by cmsimike** [comment]
Looking forward to the 3.0 release. Just recently discovered this lib and started building a twitter tool I need around the 3.0 docs and didn't realize it wasn't in pypi yet =/

**Comment by bear** [comment]
@cmsimike guess we better get something into pypi so you can test it :)

**Comment by bear** [comment]
v3.1 is now in PyPi and ReadTheDocs \o/
