### ISSUE TITLE
Alt-Text for Images

### ISSUE THREAD

**Issue by jeremylow** [bear/python-twitter#316]
https://blog.twitter.com/2016/alt-text-support-for-twitter-cards-and-the-rest-api

No actual documentation as to how it works yet (it seems really simple, though who knows), but I'd like to get this in, maybe shooting for 3.1. Seems like there's going to be a new ``include_alt_text`` query parameter, so changes might affect other methods.

Putting this here as a reminder.

**Comment by bear** [comment]
The place I see it documented is at https://dev.twitter.com/rest/reference/post/media/metadata/create

and alt_text is part of the json blob sent

**Comment by bear** [comment]
I started a branch for the alt-text work and added the PostMediaMetadata endpoint

PR #319

**Comment by jeremylow** [comment]
I think we forgot to close this issue back with the pull request - this is the default on Twitter's side at the moment and I think we've got it covered so I'm going to close.
