### ISSUE TITLE
TypeError: GetUserTimeline() got an unexpected keyword argument 'id'

### ISSUE THREAD

**Issue by bydeath** [bear/python-twitter#326]
I executed the example twitter-to-xhtml.py,  got "TypeError: GetUserTimeline() got an unexpected keyword argument 'id'".
the version is python-twitter (3.0rc1), and python version is 2.7.11+.

**Comment by jeremylow** [comment]
It should be ``user_id``. I'll fix the example.

**Comment by bydeath** [comment]
@jeremylow I tried the `user_id`, then got error below:

> File "twitter-to-xhtml.py", line 47, in FetchTwitter
    statuses = api.GetUserTimeline(user_id=user, count=1)
  File "build/bdist.linux-x86_64/egg/twitter/api.py", line 719, in GetUserTimeline
  File "build/bdist.linux-x86_64/egg/twitter/api.py", line 4514, in _RequestUrl
  File "build/bdist.linux-x86_64/egg/twitter/api.py", line 4339, in _BuildUrl
  File "build/bdist.linux-x86_64/egg/twitter/api.py", line 4393, in _EncodeParameters
  File "build/bdist.linux-x86_64/egg/twitter/api.py", line 4373, in _Encode
TypeError: str() takes at most 1 argument (2 given)

**Comment by jeremylow** [comment]
That example is really old and should be rewritten (the API isn't even authenticated). As a quick fix, you can pipe the output of this to a file:

```python
from __future__ import print_function
import sys
import twitter

TEMPLATE = """
<div>
  <a href="http://twitter.com/{user}">Twitter</a>: {user}<br>
  {tweet_text}<br>
  <a href="http://twitter.com/{user}/statuses/{status_id}">Posted {tweet_created}</a>
</div>
"""

CONSUMER_KEY = 'www'
CONSUMER_SECRET = 'xxx'
ACCESS_TOKEN_KEY = 'yyy'
ACCESS_TOKEN_SECRET = 'zzz'


def main(user=None):
    api = twitter.Api(CONSUMER_KEY, CONSUMER_SECRET, ACCESS_TOKEN_KEY, ACCESS_TOKEN_SECRET)
    statuses = api.GetUserTimeline(user_id=user)
    for status in statuses:
        print(
            TEMPLATE.format(user=status.user.screen_name,
                            tweet_text=status.text,
                            status_id=status.id,
                            tweet_created=status.created_at)
        )

if __name__ == '__main__':
    main(user=sys.argv[1])
```

You'll need to use your keys & tokens, but otherwise that should work. I'll leave this issue open on account of the ``str()`` error.
