### ISSUE TITLE
UnicodeEncodeError when processing Chinese characters.

### ISSUE THREAD

**Issue by bydeath** [bear/python-twitter#329]
I am using api.GetUserTimeline, an UnicodeEncodeError occurred when it get post which contains Chinese chacters. The error location is at Line 468 in twitter/models.py. The error traceback is below:

> File "/home/bruc/github/python-twitter/twitter/models.py", line 468, in __repr__
    self.text)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-28: ordinal not in range(128)

**Comment by bear** [comment]
It looks like your using the code from a github clone, but i want to make sure.

do you have a twitter post that I can use to test this against?

**Comment by jeremylow** [comment]
I am working on this problem with another branch and have a solution for some models, but am out at the moment. I can upload my in progress work tomorrow.

**Comment by bear** [comment]
@jeremylow that would be amazing - I'll be around all weekend working on projects so 👍

**Comment by bydeath** [comment]
@bear Yes, I am using the newest code cloned from this repository. You can find Chinese posts in the page `https://twitter.com/bbcchinese`.
