### ISSUE TITLE
no module named requests

### ISSUE THREAD

**Issue by tacos1313** [bear/python-twitter#335]
Trying to run a user stream and am not finding a module for "requests" when trying to import from api.py. Do I have to set these ahead of time somewhere else?

**Comment by jeremylow** [comment]
Yep, so if you've cloned the repository to your computer as opposed to installing it through ``pip``, then you'll need to install the dependencies as well. There are two for general, production use of python-twitter: 

* [requests](http://docs.python-requests.org/en/latest/) and 
* [requests Oauth](https://requests-oauthlib.readthedocs.io/en/latest/)

You can install both with:
    pip install requests requests-oauth

or (if you cloned the repo and are in the python-twitter directory):

    pip install -r requirements.txt

If you're planning on contributing to the library (which would be awesome), I'd probably say install the testing dependencies as well with:

    pip install -r requirements.testing.txt

If you don't want to clutter up your system version of python with a lot of dependencies, check out using a virtual environment. [Pyenv](https://github.com/yyuu/pyenv) with its [virtualenv plugin](https://github.com/yyuu/pyenv-virtualenv) are what I use.

**Comment by tacos1313** [comment]
Hi Jeremy, 

Sorry it's taken me so long to get back to you. Thanks to your help and a friend I realized I've been doing everything wrong. I'm redoing my python environment using virtualenv and now trying to figure out getting Pyenv to work. 

Once I get a little further again I would love to explore the library and will attempt my best to contribute. 

Thank you again for your help. It was greatly appreciated.
