### ISSUE TITLE
"No module named '_file_cache'" when importing

### ISSUE THREAD

**Issue by EbearPlays** [bear/python-twitter#336]
So I've been attempting some really simple stuff to get a feel for the API, but it's not really working.

```
When trying to run any of my programs, I'm met with this:
E:\Python\python.exe E:/Bot/bot.py
Traceback (most recent call last):
  File "E:/Bot/bot.py", line 12, in <module>
    import twitter
  File "E:\Python\lib\site-packages\twitter\__init__.py", line 31, in <module>
    from _file_cache import _FileCache
ImportError: No module named '_file_cache'

Process finished with exit code 1
```
Not really sure what to do here, if anyone could shed some light on it, I'd really appreciate it. Thanks!

**Comment by bloodywing** [comment]
Hi try this:
pip install python-twitter==3.0rc1

**Comment by jeremylow** [comment]
You can now use ``pip install python-twitter==3.1``, which is the latest version as of yesterday night.
