### ISSUE TITLE
changes to character counting

### ISSUE THREAD

**Issue by jeremylow** [bear/python-twitter#338]
Leaving this here so we can track as it rolls out

https://blog.twitter.com/express-even-more-in-140-characters

**Comment by jeremylow** [comment]
https://blog.twitter.com/2016/doing-more-with-140-characters

**Comment by bear** [comment]
Just woke up, saw this and popped over to make a tracking issue... thanks @jeremylow !

**Comment by jeremylow** [comment]
Yep! Here's the more technical descriptions

https://dev.twitter.com/overview/api/upcoming-changes-to-tweets

**Comment by pseudomonas** [comment]
This change seems now to be live; tweets are truncated by default. Would like to be able to switch on the tweet_mode=extended parameter in the rest API as described in @jeremylow's link https://dev.twitter.com/overview/api/upcoming-changes-to-tweets

**Comment by bear** [comment]
@jeremylow do we have something in the queue for this?

**Comment by jeremylow** [comment]
I'm working on it this weekend. A lot of tests are failing because of 
the added parameters, so I'm working through those now.

**Comment by jeremylow** [comment]
Just pushed a partial implementation if anyone wants to give it a shot.

- [ ] exclude_reply_user_ids
- [ ] auto_populate_reply_metadata
- [ ] attachment_url

- [ ] tweet_mode
- [ ] update Status model

- [ ] error handling

So basically, the consumption of tweets should work as expected, but there's some missing implementation on the posting & error handling.

**Comment by jeremylow** [comment]
Error handling seems to work with our current implementation, so I'm going to leave as is and not worry about the new status codes - those should be easy enough to handle on the user side.

Here's a question: 

So there's this `attachment_url` parameter, which basically acts like this: if the user specifies the `attachment_url` (which shall be "a single URL entity that identifies an attachment resource: currently, one to four photos, a GIF, video, poll, Quote Tweet, or DM deep link") then that doesn't count against the 140 characters, but if you just use the normal post media, attach media pipeline, then this is going to count against your 140 characters (I think - this is how it's described in the docs). This is our current pipeline and, anecdotally, this is how it _seems_ to work in tweetdeck. 

Unfortunately, we can't currently generate _one url_ for _four images_; I assume Twitter can, but like polls, this isn't available via the REST API. Therefore, if a user were to come along, upload four images, attach all of them via the `media` param, that user would (rightly) think that those will not count against the 140 characters, but since we can't generate a single URL for those four images, I think the reality is going to be different from the expectation. Not really sure how to square that circle.

**Comment by bear** [comment]
I've seen other libraries pick one of the four to use as the url that isn't counted and then add the rest to the mix, for ours maybe let's go with "pick the first one in the list" and see how that plays out

**Comment by jeremylow** [comment]
@bear Do you have a reference for that? I can't figure out a way to get a url from a media id, which is the only thing I'm getting back from twitter after uploading an image.

**Comment by bear** [comment]
@jeremylow nothing I can point you to - they were all conversations with some other twitter api consumer friends who had to deal with this. Twitter has changed a lot of little things I feel to force people to use their cards for anything media related
