### ISSUE TITLE
/accounts/update_profile_background_image.json is deprecated

### ISSUE THREAD

**Issue by jeremylow** [bear/python-twitter#341]
Which means that Api.UpdateBackgroundImage() is broken. @bear how do you want to handle? Twitter's documentation doesn't say anything about it, but this maybe happened around June or July of last year.

http://mashable.com/2015/07/20/twitter-removes-backgrounds/

I think it was finally killed off sometime after that. Do we want to delete the method entirely or put in a warning? Since Twitter is returning a hard error, I feel like deletion is OK.

**Comment by jeremylow** [comment]
For posterity, this is what is was before:

https://web.archive.org/web/20150321135709/https://dev.twitter.com/rest/reference/post/account/update_profile_background_image

**Comment by bear** [comment]
IMO we need to make it a deprecation warning for one release cycle and the delete it.

having the code fail hard because a method is missing is much worse than having twitter return an error that is handled by downstream code
