### ISSUE TITLE
Error in UploadMediaChunked

### ISSUE THREAD

**Issue by WesleyJohnson** [bear/python-twitter#345]
Getting this error anytime I try to upload a file larger than the default chunk size.

```
TypeError: str() takes at most 1 argument (2 given)
```

This is happening on this line: https://github.com/bear/python-twitter/blob/master/twitter/api.py#L1132 and I'm using python 2.7.

**Comment by jeremylow** [comment]
Confirmed & have fix. Just working on tests.

**Comment by jeremylow** [comment]
Just pushed branch ``fix/issue345`` which should address python27 compatibility.

**Comment by WesleyJohnson** [comment]
Fantastic, thank you for the quick action. I'll get our dependencies looking at this branch sometime later today and take 'er for a spin.

**Comment by jeremylow** [comment]
Just merged to master with 44dd464128a7a71563d0f37fed6f72564cbf543c
