### ISSUE TITLE
Twitter Utils return incorrect status length.

### ISSUE THREAD

**Issue by WesleyJohnson** [bear/python-twitter#346]
The *calc_expected_status_length* def in *twitter_utils.py* is returning an incorrect status length when feeding it decimals.

```
import twitter
print twitter.twitter_utils.calc_expected_status_length('72.00')
```

This returns 23 instead of 5. Something is screwy with the Regex.
https://github.com/bear/python-twitter/blob/b49b10350e98c30a67343ca0788a7f98ffd25e58/twitter/twitter_utils.py#L144

**Comment by jeremylow** [comment]
Technically that's a valid IP address, but yeah, I can see how that gets annoying. From `man inet`:

```
a.b     Part a specifies the first byte of the binary address.   Part
        b is interpreted as a 24-bit value that defines the rightmost
        three bytes of the binary address.  This notation is suitable
        for specifying (outmoded) Class A network addresses.
```

Since Twitter isn't recognizing it as an IP address, we should mirror their behavior and say it isn't.

**Comment by WesleyJohnson** [comment]
Interesting, I didn't know that was considered a valid IP. Twitter's determination of what is and isn't an address seems pretty extensive when looking at their twitter-text lib: https://github.com/twitter/twitter-text/blob/master/js/twitter-text.js It seems like a non-trivial task to port that over to python.

**Comment by jeremylow** [comment]
Yeah we take a slightly more liberal approach in a few cases, but our lib is based off of that. 

Jeremy Low


		_____________________________

**Comment by WesleyJohnson** [comment]
I discovered the option to disable tweet length verification in the PostUpdate using the verify_status_length arg. I'm using that to get around this which works well enough for my needs. Thanks!

**Comment by jeremylow** [comment]
Lands in development with 3.2dev0 ( PR #394 )
