### ISSUE TITLE
TypeError: str() takes at most 1 argument (2 given)

### ISSUE THREAD

**Issue by ydatech** [bear/python-twitter#348]
Hallo Everyone.

I tried to post twitter status with a media in it (by using url) . and I got this error:

`TypeError: str() takes at most 1 argument (2 given)`

Here is my code : 

```

message = "It✔️s[#ｉｎｆｏｇｒａｐｈｉｃｓ]❤Com: #comics & #infographic explain how #Zika #Virus spread ItsIN.ga/pa8wx #ZikaVirus"

picture="http://www.valuewalk.com/wp-content/uploads/2016/01/the-best-and-worst-trades-of-all-time.jpg"

post = api.PostUpdate(message,media=picture)
```

I try to find out the problem.. and I found many code like this in api.py file:
```
if isinstance(status, str) or self._input_encoding is None:
            u_status = status
        else:
            u_status = str(status, self._input_encoding)
```

As I know that str() only support one argument , refer to this https://docs.python.org/2/library/functions.html#str

So , what should I do to resolve the issue..

Thanks in advance..

**Comment by jeremylow** [comment]
I think the issue is the same as #345 based on testing your code above. If you could give it a shot using the latest from the master branch, that'd be great.

**Comment by ydatech** [comment]
@jeremylow  thank you. now it works properly..
