### ISSUE TITLE
twitter.error.TwitterError  {'message': 'Media type could not be determined.}

### ISSUE THREAD

**Issue by ydatech** [bear/python-twitter#352]
When I tried to post media from url (facebook cdn), I got this error:
`twitter.error.TwitterError  {'message': 'Media type could not be determined.}`

here my code:
```
message = " This is my tweet with photo"
picture="http://graph.facebook.com/591990197635863/picture?type=normal"
post = api.PostUpdate(message,media=picture)
```

I also tried to post the media via PHP library, and it works fine...

image urls:
http://graph.facebook.com/591990197635863/picture?type=normal
http://graph.facebook.com/591338477701035/picture?type=normal
http://graph.facebook.com/591736000994616/picture?type=normal
http://graph.facebook.com/590131681155048/picture?type=normal
http://graph.facebook.com/588396287995254/picture?type=normal
etc..

**Comment by ydatech** [comment]
I think this error source is  parse_media_file function in twitter_utils.py 
I found that media_type variable from facebook cdn is None
```
None
Traceback (most recent call last):
  File "trytwitter.py", line 15, in <module>
    status = api.PostUpdate('I love python-twitter!',media="http://graph.facebook.com/590131681155048/picture?type=normal")
  File "build\bdist.win32\egg\twitter\api.py", line 986, in PostUpdate
  File "build\bdist.win32\egg\twitter\twitter_utils.py", line 239, in parse_media_file
twitter.error.TwitterError: {'message': 'Media type could not be determined.'}
```

so "Media type could not be determined." error raised.

What should I do ?

**Comment by ydatech** [comment]
This is my solution but I think it's not best practice.
I added conditional to pass the validation if media_type is None..
```
if not media_type is None:
        if media_type in img_formats and file_size > 5 * 1048576:
            raise TwitterError({'message': 'Images must be less than 5MB.'})
        elif media_type in video_formats and file_size > 15 * 1048576:
            raise TwitterError({'message': 'Videos must be less than 15MB.'})
        elif media_type not in img_formats and media_type not in video_formats:
            raise TwitterError({'message': 'Media type could not be determined.'})
```

What do you think ? It works fine for me..

**Comment by bear** [comment]
I like incrementally solving current issues and not worrying too much about does it solve all issues...

so yes, +1 to your solution - would love to merge a PR if you are willing to create one.

**Comment by bear** [comment]
thanks for the PR and the work to get this fixed!
