### ISSUE TITLE
Possible error in method GetUserSuggestion

### ISSUE THREAD

**Issue by btr1975** [bear/python-twitter#355]
I get this error when trying to use this method:

Traceback (most recent call last):
  File "./Twitter.py", line 145, in <module>
    main()
  File "./Twitter.py", line 137, in main
    print(api_obj.GetUserSuggestion(category))
  File "/home/btr75/py3virtualenv/Twitter/lib/python3.4/site-packages/twitter/api.py", line 543, in GetUserSuggestion
    url = '%s/users/suggestions/%s.json' % (self.base_url, category.Slug)
AttributeError: 'Category' object has no attribute 'Slug'

I notice that the category object has "slug", not "Slug".

If I edit this line:
url = '%s/users/suggestions/%s.json' % (self.base_url, category.Slug)

to this instead:
url = '%s/users/suggestions/%s.json' % (self.base_url, category.slug)

It works, I don't believe I am using it wrong, but let me know.

Thanks,
    Ben

**Comment by jeremylow** [comment]
Yeah, that happened when we removed the `@properties` from the models. Sorry about that. Just pushed a fix.

**Comment by jeremylow** [comment]
Merged to master with  91f0be2
