### ISSUE TITLE
Inconsistent rate limit behavior

### ISSUE THREAD

**Issue by jeremylow** [bear/python-twitter#358]
If the Api isn't instantiated with `sleep_on_rate_limit=True`, then the `Api.rate_limit` object doesn't actually decrement the `remaining` value on any of the end points, even after calling `api.InitializeRateLimit()`. Since that might be valuable information, it seems like we should retain it. First impression is that the offending code is L4821:

```python
if url and self.sleep_on_rate_limit:
    limit = self.CheckRateLimit(url)

    if limit.remaining == 0:
        try:
            time.sleep(int(limit.reset - time.time()))
        except ValueError:
            pass
```

Seems to me that the `if url and self.sleep_on_rate_limit` check should be `if url and self.rate_limit` and the `if limit.remaining` should be `if limit.remaining and self.sleep_on_rate_limit` so that if the user wants to have access to the `rate_limit` object, they can do so by calling `api.InitializeRateLimit()` and then they'd have access to the `rate_limit` object and it would properly keep track of its resource limits.

**Comment by jeremylow** [comment]
One more place (L4851):

```python
# could just be if url and self.rate_limit:
if url and self.sleep_on_rate_limit and self.rate_limit:
    limit = resp.headers.get('x-rate-limit-limit', 0)
    remaining = resp.headers.get('x-rate-limit-remaining', 0)
    reset = resp.headers.get('x-rate-limit-reset', 0)

    self.rate_limit.set_limit(url, limit, remaining, reset)
```

**Comment by bear** [comment]
Your analysis and solution both make sense - good job!

**Comment by zetasyanthis** [comment]
Is it possible this is causing these errors I'm seeing? Note that the first line is a print of limit.reset inserted right before the traceback occurs.

1468173543
Traceback (most recent call last):
  File "./src/myarchive/main.py", line 108, in <module>
    main()
  File "./src/myarchive/main.py", line 81, in main
    username=args.username)
  File "/mnt/bulk/repos/projects/myarchive/src/myarchive/twitterlib.py", line 134, in archive_tweets
    include_entities=True)
  File "/usr/local/lib/python2.7/dist-packages/twitter/api.py", line 3361, in GetFavorites
    resp = self._RequestUrl(url, 'GET', data=parameters)
  File "/usr/local/lib/python2.7/dist-packages/twitter/api.py", line 4753, in _RequestUrl
    time.sleep(int(limit.reset - time.time()))
IOError: [Errno 22] Invalid argument
