### ISSUE TITLE
Make test , make coverage failed 

### ISSUE THREAD

**Issue by MedocIAS** [bear/python-twitter#362]
Hi,
Executing 'make test' & 'make coverage' I ve got an import failure on line 
  from six import wraps

See log files attached : 
[python-twitter_makecoverage.txt](https://github.com/bear/python-twitter/files/357337/python-twitter_makecoverage.txt)
[python-twitter_maketest.txt](https://github.com/bear/python-twitter/files/357338/python-twitter_maketest.txt)

Best Regards,

**Comment by bear** [comment]
Are you doing a `make dev` to get the modules that testing requires to be installed?

**Comment by jeremylow** [comment]
Looking around, seems like this isn't an uncommon problem. Perhaps some of the solutions here can help? 

http://stackoverflow.com/questions/31417964/importerror-cannot-import-name-wraps

**Comment by MedocIAS** [comment]
Hi,
 
@bear
I did follow README.rst , so yes I did make dev first ,and then make test 

@jeremylow 
Thanks it did help.
pip freeze | grep -e six -e mock
mock==2.0.0
six==1.10.0

But within ipython : 
In [1]: import six
In [2]: six.__version__
Out[2]: '1.5.2'

So my solution was :
apt-get purge python-six

then within ipython : 
In [1]: import six
In [2]: six.__version__
Out[2]: '1.10.0'

make test and make coverage ok now.

Best regards

**Comment by MedocIAS** [comment]
An enhancement would be to check the version of six in the requirements ...

**Comment by bear** [comment]
great idea, no idea why we didn't have that already in the testing requirements.

if this works for you, please do close the issue - I'll close it in a week or so if you don't report back it doesn't solve the issue.

thanks!

**Comment by jeremylow** [comment]
I think we had overlapping requirements from requests, which was pulling in a later version of six, which hid the issue.
