### ISSUE TITLE
Location stream throws TwitterError

### ISSUE THREAD

**Issue by rajasimon** [bear/python-twitter#363]
```
>>> for line in twitter_api.GetStreamFilter(locations=["2.1,41.1,2.3,41.5"]):
...     Print line
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/simon/Nightyspace/venv/lib/python2.7/site-packages/twitter/api.py", line 4430, in GetStreamFilter
    data = self._ParseAndCheckTwitter(line.decode('utf-8'))
  File "/Users/simon/Nightyspace/venv/lib/python2.7/site-packages/twitter/api.py", line 4696, in _ParseAndCheckTwitter
    raise TwitterError({'message': "json decoding"})
twitter.error.TwitterError: {'message': 'json decoding'}
>>> 
```

How can I debug this ?

**Comment by rajasimon** [comment]
Wait a minute... I didn't see any error when I running this in cloud. But why this error in my local only ah ?

**Comment by bear** [comment]
We seem to have two problems happening - one is that when Twitter returns a 401 (Authorization Required) we are trying to parse the html as json .

The other is that our request seems to be different than what the sample dev.twitter.com OAUTH test generates.

I'm looking into both today.

**Comment by bear** [comment]
still chewing on this - we may be getting hit by a change to how twitter OAuth1 requests are made - debugging now

**Comment by rajasimon** [comment]
Is it stream only down ? Or other Api also ?

**Comment by bear** [comment]
turns out my test had a bad cut-n-paste issue!  The OAuth is fine, it was an error handling only change which I have a branch testing now.

I should be able to merge this in a couple minutes

**Comment by bear** [comment]
ok, please do test this with the latest github code. If you confirm i'll push a release to PyPI

**Comment by rajasimon** [comment]
`127.0.0.1 - - [12/Jul/2016 02:07:51] "GET /twitter_streaming/?location=40.74900,-73.96807&name_id=nyc&status=start HTTP/1.1" 200 -
Process MultiProcess-1:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/Users/simon/Nightyspace/socialtrendly/helper/multi_process.py", line 23, in run
    for line in twitter_api.GetStreamFilter(locations=test_instance):
  File "build/bdist.macosx-10.12-intel/egg/twitter/api.py", line 4504, in GetStreamFilter
    data = self._ParseAndCheckTwitter(line.decode('utf-8'))
  File "build/bdist.macosx-10.12-intel/egg/twitter/api.py", line 4780, in _ParseAndCheckTwitter
    return data
UnboundLocalError: local variable 'data' referenced before assignment`

Initial error is gone now but when I integrated into my web service this error coming...

**Comment by bear** [comment]
how are you installing python-twitter? from github and then a call to `make env` or ???

**Comment by bear** [comment]
ohhhh - I know what that is

**Comment by rajasimon** [comment]
Oaky. Why is unauthenticated?  It it problem with my python-twitter setup or credential?

**Comment by bear** [comment]
ok, fix for that is pushed - I'm suspecting that your core issue is with credentials.

If your using Python v3 you can do `python get_access_token.py` to have it walk thru a token request "dance". That is what I did to test that this change was working.

**Comment by jeremylow** [comment]
There's also a guide here: http://python-twitter.readthedocs.io/en/latest/getting_started.html if you want to confirm that you're using the correct access tokens with the correct application

**Comment by bear** [comment]
@rajasimon would it be ok if we close this bug, since it was dealing with the exception.

If you find that the docs that @jeremylow referenced doesn't work, could you open a new issue?

thanks!

**Comment by rajasimon** [comment]
Okay we can close this issue right now. And nice error handling by the way. My twitter apps is messed up. And the code is working in the normal cloud. If I found any bugs I will open a new issue. Thank you so much.

**Comment by bear** [comment]
@rajasimon just so you know, I use the streaming example https://github.com/bear/python-twitter/blob/master/examples/streaming/track_users.py  for testing so you may be able to use that as code to compare against.

**Comment by eufelipemateus** [comment]
Still not working i put a list with locations but is return with error.
