### ISSUE TITLE
ImportError: No module named '_file_cache' on Python3

### ISSUE THREAD

**Issue by nickchuck** [bear/python-twitter#365]
I get the following error when i try and use python-twitter with python 3:

`Traceback (most recent call last):
  File "tweetit.py", line 1, in <module>
    import twitter
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/twitter/__init__.py", line 31, in <module>
    from _file_cache import _FileCache
ImportError: No module named '_file_cache'`

**Comment by bear** [comment]
hi @nickchuck - what version of python-twitter are you using, I think this issue was fixed as 
https://github.com/bear/python-twitter/issues/336

**Comment by nickchuck** [comment]
Here's what pip show returned:

Metadata-Version: 2.0
Name: python-twitter
Version: 2.2
Summary: A Python wrapper around the Twitter API
Home-page: https://github.com/bear/python-twitter
Author: The Python-Twitter Developers
Author-email: python-twitter@googlegroups.com
Installer: pip
License: Apache License 2.0
Location: /Library/Python/2.7/site-packages
Requires: requests, requests-oauthlib
Classifiers:
  Development Status :: 5 - Production/Stable
  Intended Audience :: Developers
  License :: OSI Approved :: Apache Software License
  Operating System :: OS Independent
  Topic :: Software Development :: Libraries :: Python Modules
  Topic :: Communications :: Chat
  Topic :: Internet
  Programming Language :: Python
  Programming Language :: Python :: 2
  Programming Language :: Python :: 2.7
  Programming Language :: Python :: 3
  Programming Language :: Python :: 3.3

**Comment by bear** [comment]
yea, the latest release is v3.1 and should have this issue fixed.

**Comment by nickchuck** [comment]
Oops, just upgraded to 3.1:

Metadata-Version: 1.1
Name: python-twitter
Version: 3.1
Summary: A Python wrapper around the Twitter API
Home-page: https://github.com/bear/python-twitter
Author: The Python-Twitter Developers
Author-email: python-twitter@googlegroups.com
License: Apache License 2.0
Location: /Library/Python/2.7/site-packages
Requires: future, requests, requests-oauthlib
Classifiers:
  Development Status :: 5 - Production/Stable
  Intended Audience :: Developers
  License :: OSI Approved :: Apache Software License
  Operating System :: OS Independent
  Topic :: Software Development :: Libraries :: Python Modules
  Topic :: Communications :: Chat
  Topic :: Internet
  Programming Language :: Python
  Programming Language :: Python :: 2
  Programming Language :: Python :: 2.7
  Programming Language :: Python :: 3
  Programming Language :: Python :: 3.5

I still however get the same error. Looks like the issue is probably on my side though. Thanks!

**Comment by bear** [comment]
@nickchuck you may have a left over _file_cache directory or a .pyc -- if your still having the issue please do re-open and we can get more info to find out the solution.

If your installing from github - then make sure to run `make clean` before installing.

**Comment by nickchuck** [comment]
Looks like it was a cache thing! It's all working now. Thanks for the help! Very kind of you.

**Comment by bear** [comment]
@nickchuck \o/ glad we could help!
