### ISSUE TITLE
SSL Connection error

### ISSUE THREAD

**Issue by vishnuraju** [bear/python-twitter#368]
This is the error when trying 

EOF occurred in violation of protocol (_ssl.c:590)

**Comment by bear** [comment]
trying what? can give an example or the python-twitter call you were trying to make?

**Comment by jeremylow** [comment]
@vishnuraju This looks like a python ssl problem or a problem with requests. See https://github.com/kennethreitz/requests/issues/3391 for a possible solution. 

I'm going to close this issue since it's not specific to python-twitter. Please reopen if that is incorrect.
