### ISSUE TITLE
Update GetTrendsWoeid to include count

### ISSUE THREAD

**Issue by JSpotMan** [bear/python-twitter#374]
Twitter API makes available the number of count for each trend but it not currently included in the GetTrendsWoied. Can this be updated?

Thanks!
J

**Comment by jeremylow** [comment]
I'm not seeing that available on :

https://dev.twitter.com/rest/reference/get/trends/available or
https://dev.twitter.com/rest/reference/get/trends/place

Are those the endpoints to which you're referring or am I missing something?

**Comment by JSpotMan** [comment]
Hi Jeremy,

Yes, it is here https://dev.twitter.com/rest/reference/get/trends/place.

If you look at the example results one of the variables it returns is
"tweet_volume"

Is there any way to collect this?

Thanks.

**Comment by jeremylow** [comment]
That should be populated under the volume attribute of the Trend objects

**Comment by JSpotMan** [comment]
I got it. Thanks.

I appreciate your fast feedback.
J

**Comment by jeremylow** [comment]
It's not being populated though, so I just pushed a fix. Will let you know when it hits master.

**Comment by jeremylow** [comment]
This has landed in master with pr #375
