### ISSUE TITLE
make dev error with pypy5.3 binary distribution on 64-bit linux

### ISSUE THREAD

**Issue by jeremylow** [bear/python-twitter#378]
Hey @bear - with the latest Makefile changes, I'm getting this error running `make dev`. Not sure if there's a way to catch this error within the make command and compile from the alternative, but I figure it's worth noting.

```
pyenv install -s pypy-5.3

ERROR: The binary distribution of PyPy is not available for linux64.
try 'pypy-5.3-src' to build from soruce.

make: *** [Makefile:18: dev] Error 1
```

**Comment by bear** [comment]
we can add OS if checks to avoid that command and tox silently skips not present binaries... let me find an example...

**Comment by jeremylow** [comment]
Lordy that takes forever to compile, but yeah, it works! Syntax was a little different on my system, so I'll open a PR and you can check it out? Make's always been a mystery to me, so another set of eyes is definitely welcome.

Tox is looking for a pypy3 install, but make dev doesn't provide. Looking at http://pypy.org/download.html , the latest binary for pypy3 is an alpha release and doesn't work on Windows, which isn't great. Which would you want to test against? pyenv lists:
```
  pypy3-dev
  pypy3-portable-2.3.1
  pypy3-portable-2.4
  pypy3-2.3.1-src
  pypy3-2.3.1
  pypy3-2.4.0-src
  pypy3-2.4.0
  pypy3.3-5.2-alpha1-src
  pypy3.3-5.2-alpha1
```

**Comment by bear** [comment]
We should probably pull something from this list for linux: https://github.com/squeaky-pl/portable-pypy#portable-pypy-distribution-for-linux
