### ISSUE TITLE
Errors when running test

### ISSUE THREAD

**Issue by gurgi23** [bear/python-twitter#392]
I am having trouble when running the tests.
When I run $ make test it appears error 127.
When I run $ make coverage it finds 3 errors. (this is what appears in red)
ERROR collecting tests/test_api_30.py _____________________
ImportError while importing test module '/Users/georginacamps/python-twitter/tests/test_api_30.py'.
Original error message:
'No module named responses'
Make sure your test modules/packages have valid Python names.
__________________ ERROR collecting tests/test_rate_limit.py ___________________
ImportError while importing test module '/Users/georginacamps/python-twitter/tests/test_rate_limit.py'.
Original error message:
'No module named responses'
Make sure your test modules/packages have valid Python names.
____________________ ERROR collecting tests/test_unicode.py ____________________
ImportError while importing test module '/Users/georginacamps/python-twitter/tests/test_unicode.py'.
Original error message:
'No module named responses'
Make sure your test modules/packages have valid Python names.
!!!!!!!!!!!!!!!!!!! Interrupted: 3 errors during collection !!!!!!!!!!!!!!!!!!!!
=========================== 3 error in 0.51 seconds ============================
I would like to know how can I fix it.
Thank you

**Comment by jeremylow** [comment]
Run `make dev` first or `pip install -Ur requirements.testing.txt`

**Comment by gurgi23** [comment]
Thanks! I did it before and it did not work, but now it did :)

**Comment by jeremylow** [comment]
You can try some of the solutions here:

http://stackoverflow.com/questions/6048085/writing-unicode-text-to-a-text-file
