### ISSUE TITLE
GetMentions "rate limit exceeded", but rate checker reporting back 15?

### ISSUE THREAD

**Issue by RedactedProfile** [bear/python-twitter#393]
So in my bot, I do a check for the rate limit, before even trying to perform a get for mentions. After my bots been running for a few minutes, it begins to error out in my reply checker routine

Even with the `CheckRateLimit` service against `statuses/mentions_timeline` reports back `15` remaining, eventually after a few minutes the following exception gets thrown 

As seen in the full stacktrace below `twitter.error.TwitterError: [{'code': 88, 'message': 'Rate limit exceeded'}]`. 

> Traceback (most recent call last):
>   File "C:/Users/Kyle/Desktop/KyBot/bot.py", line 300, in reply
>     mentions = action.mentions(since_id=since_id)
>   File "C:/Users/Kyle/Desktop/KyBot/bot.py", line 35, in mentions
>     mentions = self.api.GetMentions(since_id=since_id)
>   File "C:\Users\Kyle\AppData\Local\Programs\Python\Python35-32\lib\site-packages\twitter\api.py", line 3431, in GetMentions
>     data = self._ParseAndCheckTwitter(resp.content.decode('utf-8'))
>   File "C:\Users\Kyle\AppData\Local\Programs\Python\Python35-32\lib\site-packages\twitter\api.py", line 4688, in _ParseAndCheckTwitter
>     self._CheckForTwitterError(data)
>   File "C:\Users\Kyle\AppData\Local\Programs\Python\Python35-32\lib\site-packages\twitter\api.py", line 4715, in _CheckForTwitterError
>     raise TwitterError(data['errors'])
> twitter.error.TwitterError: [{'code': 88, 'message': 'Rate limit exceeded'}]

here is the code leading up to that:

``` python
    mentions_rate = action.rate('statuses/mentions_timeline')
            if mentions_rate > 0:
                # get our latest reply id
                since_id = query.fetch_latest_reply_id()
                # go through each reply (if there are any)
                mentions = action.mentions(since_id=since_id)
```

action.rate looks like this

``` python
    def rate(self, service):
        """
        Returns the remaining rate limit for a service
        :param str service:
        :return int :
        """
        limit = self.api.CheckRateLimit("https://api.twitter.com/1.1/{}.json".format(service))
        return limit.remaining
```

action.mentions looks like this

``` python
    def mentions(self, since_id=None):
        """
        :return list:
        """
        mentions = self.api.GetMentions(since_id=since_id)
        return mentions
```

Am I checking the right services rates?

**Comment by jeremylow** [comment]
Looks like it. What's the version you're using?

-- 
Jeremy Low

**Comment by RedactedProfile** [comment]
Whichever version is currently latest on PIP, i think it was 3.1 I believe
it was. It had a bug where getting the suggested categories members,
wouldn't take because the method wanted a Categogy object so it could read
its "Slug" property, which wouldn't work as they were constructed to have
"slug" for example.

This bug has already been addressed i saw, just not published to pip yet i
guess

Cheers!

**Comment by jeremylow** [comment]
@RedactedProfile If you're good with the new version, can I close this issue?
