### ISSUE TITLE
Problem getting screen_name from search API

### ISSUE THREAD

**Issue by alliocha1805** [bear/python-twitter#395]
I'm trying to search Specific tweets and then retweet them and follow their poster .

I have this code to identify a Tweet Id + Screen name of poster : 

`import twitter
import os
import json

consumer_key="blabla"
consumer_secret="blabla"
access_token_key="blabla"
access_token_secret="blabla"
api = twitter.Api(consumer_key,
                  consumer_secret,
                  access_token_key,
                  access_token_secret)
# Recherche API des tweets

results = api.GetSearch(raw_query="q=rt%20follow%20gagner%20lang%3Afr")
# Parsing JSON

for elt in results:
    json_string=str(elt)
    parsed_json=json.loads(json_string)
    id_tweet=parsed_json['id_str']
    try:
        nom=parsed_json['screen_name']
    except:
        nom="bug"
    print(id_tweet)
    print(nom)

os.system("PAUSE")`

With this code i find ID of Tweet with no problem but it's impossible to get the "screen_name" value from the search (it always print "bug" according to the exception in the code .

How can i get this info ?

A big Thanks in advance for your help ;)

**Comment by jeremylow** [comment]
It's should be `parsed_json["user"]["screen_name"]`

You can access that directly from the tweet returned:
```
for elt in results:
    id = elt.id_str
    screenname = elt.user.screen_name
```
Without having to convert to a string and then back to json

-- 
Jeremy Low

**Comment by jeremylow** [comment]
It should be `parsed_json["user"]["screen_name"]`

You can access that directly from the tweet returned:
```
for elt in results:
    id = elt.id_str
    screenname = elt.user.screen_name
```
Without having to convert to a string and then back to json
