### ISSUE TITLE
PostRetweet with comment

### ISSUE THREAD

**Issue by rawxfish** [bear/python-twitter#396]
Hi, is it possible to retweet with comments like this:
![image](https://cloud.githubusercontent.com/assets/1312469/19838342/9dac0176-9ea3-11e6-9ebb-01458ae47f45.png)

**Comment by jeremylow** [comment]
Call `PostUpdate()` with the tweet's permalink as the last part of the status:

```python
api.PostUpdate(status='eyes emoji https://twitter.com/himawari8bot/status/792758238227955713')
```

See here https://twittercommunity.com/t/method-to-retweet-with-comment/35330/5
