### ISSUE TITLE
Problem to retweet et follow someone

### ISSUE THREAD

**Issue by alliocha1805** [bear/python-twitter#402]
Hi all,

I have a script to identify certain tweet (script from issue https://github.com/bear/python-twitter/issues/395 )

The script works well to identify the Tweets but i have trouble with retweeting/following the person whi posted these tweets 

The piece of code (i didn't put the credentials/identification to API etc..) : 
```python
results = api.GetSearch(raw_query="q=rt%20follow%20gagner%20lang%3Afr")
    
#Parsing JSON

for elt in results:
    id_tweet = elt.id_str
    screenname = elt.user.screen_name
    print(id_tweet)
    print(screenname)
    #retweet+follow
    twitter.api.Api.PostRetweet(id_tweet, trim_user=True)
    print("retweet : ",id_tweet)
    twitter.api.Api.CreateFriendship(screen_name=screenname)
    print("Follow: ",screen_name)
    #pause
    time.sleep(15)
print("Successful script!")
os.system("PAUSE")
```
I have the error "TypeError: PostRetweet() missing 1 required positional argument: 'status_id'" with the line of retweet and the error "TypeError: CreateFriendship() missing 1 required positional argument: 'self'" with the line of following .

I think i have missed something in the documentation but i don't see what.

Thanks i advance for your help ;)

**Comment by jeremylow** [comment]
`twitter.api.Api.PostRetweet(id_tweet, trim_user=True)` and `twitter.api.Api.CreateFriendship(screen_name=screenname)` should be `api.PostRetweet(id_tweet, trim_user=True)` and `api.CreateFriendship(screen_name=screenname)`

**Comment by alliocha1805** [comment]
Thanks it works with no error but it don't follow the people it tell him to follow Oo. 

The retweet works well, no error for the api.CreateFriendship(screen_name=screenname) but on the account it didn't follow the people i have retweeted

**Comment by jeremylow** [comment]
what's the output of `api.CreateFriendship(screen_name=screenname)`

**Comment by alliocha1805** [comment]
I don't ask any output in my code, just to "create" the friend ship . Here's the final code : 

`results = api.GetSearch(raw_query="q=rt%20follow%20gagner%20lang%3Afr")


    
#Parsing JSON

for elt in results:
    id_tweet = elt.id_str
    screenname = elt.user.screen_name
    print(id_tweet)
    print(screenname)
    #retweet+follow
    try:
        api.PostRetweet(id_tweet, trim_user=True)
        print("retweet : ",id_tweet)
    except:
        print("erreur surement deja RT")
    
    try:
        api.CreateFriendship(screen_name=screenname)
        print("Follow: ",screen_name)
    except:
        print("erreur, surement deja follow")
    
    #pause
    time.sleep(15)
print("Successful script!")
os.system("PAUSE")`

**Comment by jeremylow** [comment]
Can you tell me what you get from this:

```python
results = api.GetSearch(raw_query="q=rt%20follow%20gagner%20lang%3Afr")

#Parsing JSON

for elt in results:
    id_tweet = elt.id_str
    screenname = elt.user.screen_name
    print(id_tweet)
    print(screenname)
    #retweet+follow

    user_followed = api.CreateFriendship(screen_name=screenname)
    print(user_followed)

    #pause
    time.sleep(15)
print("Successful script!")
os.system("PAUSE")
```

**Comment by jeremylow** [comment]
Also, I'm going to throw this out there: if you've already followed a bunch of people, Twitter imposes limits on the number of people you can follow. There's no published documentation to the specifics of this effect, but if you're running a script that just retweets and follows other users, that account is going to get flagged pretty quickly. 

Unless there's an error that's getting thrown by Twitter, I think you're probably running into this.

**Comment by alliocha1805** [comment]
I have tried you code and it's giving me this : 

`793795391510736896
leagauthiier
{"created_at": "Thu Apr 10 13:59:58 +0000 2014", "description": "P&T \u2728 | D \ud83d\udc98", "favourites_count": 1872, "followers_count": 151, "friends_count": 36, "id": 2474033979, "lang": "fr", "listed_count": 1, "name": "[LgDw]", "notifications": true, "profile_background_color": "000000", "profile_background_image_url": "http://abs.twimg.com/images/themes/theme1/bg.png", "profile_banner_url": "https://pbs.twimg.com/profile_banners/2474033979/1477432501", "profile_image_url": "http://pbs.twimg.com/profile_images/791035366321127425/ittKzfwj_normal.jpg", "profile_link_color": "FA743E", "profile_sidebar_fill_color": "000000", "profile_text_color": "000000", "screen_name": "leagauthiier", "status": {"created_at": "Wed Nov 02 12:42:42 +0000 2016", "hashtags": [], "id": 793795470619471872, "id_str": "793795470619471872", "lang": "fr", "retweet_count": 98, "retweeted_status": {"created_at": "Wed Nov 02 06:02:04 +0000 2016", "favorite_count": 19, "hashtags": [], "id": 793694644936798208, "id_str": "793694644936798208", "lang": "fr", "media": [{"display_url": "pic.twitter.com/iBA8ZLkoyJ", "expanded_url": "https://twitter.com/ZoroarkGives/status/793694644936798208/photo/1", "id": 793694642214666240, "media_url": "http://pbs.twimg.com/media/CwPFEmlWAAAjOw3.jpg", "media_url_https": "https://pbs.twimg.com/media/CwPFEmlWAAAjOw3.jpg", "type": "photo", "url": "https://t.co/iBA8ZLkoyJ"}], "retweet_count": 98, "source": "<a href=\"http://bufferapp.com\" rel=\"nofollow\">Buffer</a>", "text": "\u263c RT + FOLLOW pour tenter de gagner cette monoteam dragon shiny strat.\nR\u00e9sultat dans quelques jours, GL ! \u263c https://t.co/iBA8ZLkoyJ", "urls": [], "user_mentions": []}, "source": "<a href=\"http://twitter.com/download/android\" rel=\"nofollow\">Twitter for Android</a>", "text": "RT @ZoroarkGives: \u263c RT + FOLLOW pour tenter de gagner cette monoteam dragon shiny strat.\nR\u00e9sultat dans quelques jours, GL ! \u263c https://t.co/\u2026", "urls": [], "user_mentions": [{"id": 4725543507, "name": "\u2b50zoro\u2b50", "screen_name": "ZoroarkGives"}]}, "statuses_count": 1062}`

**Comment by jeremylow** [comment]
And you're still getting the issue where the following relationship isn't working?

**Comment by alliocha1805** [comment]
yup and the Twitter account is quite news with only 21 RT (over a week) + 50 follow (on a regular account i follow like 200 people so i don't think the limit is the problem)

**Comment by jeremylow** [comment]
Your search is returning the retweeted tweet and you're attempting to follow the user that posted the retweet, not the original tweet. You could filter out retweets from your search if you only want original tweets.

**Comment by alliocha1805** [comment]
Oh yeah maybe it's the problem :) I'll test your solution thanks ! (you can close the ticket)

**Comment by bear** [comment]
thanks @alliocha1805 for the original report and sticking with us during debug and testing

it's great working with devs who don't just toss an issue and then never hang around
