### ISSUE TITLE
error on startup, the script works anyways though

### ISSUE THREAD

**Issue by rgarch** [bear/python-twitter#403]
https://ptpb.pw/6o5q

I'm running ArchLinux and I have this very short python script that I use in the terminal (CLI) to access Twitter. It uses python2 and hasn't had this error until recently. I'm curious whether I should switch to python3 or if this is a bug with python-twitter? The script keeps working fine after the error but I'd like to find out why I have the error in the first place. 

Thanks

**Comment by jeremylow** [comment]
That's just a warning, so I wouldn't worry about it. It looks like we're surfacing all warnings, which I think was a holdover from me testing something, so I think we can take that out. Thanks for the report!
