### ISSUE TITLE
Issue with twitter.api 

### ISSUE THREAD

**Issue by ZarubinArtem** [bear/python-twitter#405]
Can not follow the manual in Readme. Seems like there are no actual twitter library documentation.

There are no twitter.API method

![screen shot 2016-11-16 at 11 40 11](https://cloud.githubusercontent.com/assets/7883191/20340347/26c94440-abf2-11e6-8741-8770f978dace.png)

And twitter.api doesn't work

![screen shot 2016-11-16 at 11 40 51](https://cloud.githubusercontent.com/assets/7883191/20340372/46733a12-abf2-11e6-8808-f9b4492131cf.png)

**Comment by jeremylow** [comment]
You're using http://mike.verdone.ca/twitter/ , not this library. You can install ours with `pip install python-twitter` rather than `pip install twitter`
