### ISSUE TITLE
except if tweets are protected.

### ISSUE THREAD

**Issue by rootraid** [bear/python-twitter#407]
Hello all,
I am new to the whole twitter API and python-twitter. Anyone know how to filter out protected twitter accounts from API query results?

Thanks

**Comment by jeremylow** [comment]
They should be filtered out by default if the authenticated user doesn't have access to see those tweets. Are you seeing different behavior?

**Comment by jeremylow** [comment]
For more details on how to use the search feature see here: 

https://dev.twitter.com/rest/public/search

And from our documentation: 

http://python-twitter.readthedocs.io/en/latest/searching.html
