### ISSUE TITLE
Version 3.2

### ISSUE THREAD

**Issue by jeremylow** [bear/python-twitter#408]
I think all the milestones are resolved on `develop`. How about we push to master and make a release?

**Comment by jeremylow** [comment]
lol he says as the last build failed

**Comment by jeremylow** [comment]
Apparently pypy3-2.4.0 is based on python 3.2.5, which is not supported by `pip 9.0.1`:

`pip requires Python '>=2.6,!=3.0.*,!=3.1.*,!=3.2.*' but the running Python is 3.2.5`

See [here](http://pypy.org/download.html). The pypy version based on python 3.3 is `pypy3.3-5.2-alpha1`, and I'm not sure we want to rely on an alpha. Thoughts @bear ?

**Comment by bear** [comment]
yea, let's avoid alpha for our production releases

**Comment by bear** [comment]
I just pushed PR #412 to remove pypy3 for the short term - with everything going green I would like to release 3.2 by the weekend if no one has any objections

**Comment by jeremylow** [comment]
None from me!

**Comment by bear** [comment]
I just merged the latest master changed into develop branch and it's all green

I'll get to the 3.2 release either tonight or tomorrow then!

**Comment by bear** [comment]
done!
