### ISSUE TITLE
calc_expected_status_length does not work

### ISSUE THREAD

**Issue by halcy** [bear/python-twitter#415]
calc_expected_status_length is broken in two ways right now. 

1. URL_REGEXP only recognizes URLs at the start of a string, which is correct for is_url, but for calc_expected_status_length, all URLs should be detected, not just URLs at the start of the tweet. There should be a different URL_REGEXP for calc_expected_status_length without the start-of-string makers.
2. The URL regex has multiple groups, so findall returns a list of tuples, not strings. If there are matches, replaced_chars = len(''.join(match)) crashes, it should be replaced_chars = len(''.join(map(lambda x: x[0], match))) instead

**Comment by jeremylow** [comment]
Thanks for the report - can you check out branch `fix/issue415` and see if that solves the above?

**Comment by halcy** [comment]
Thank you for the quick fix. Seems to work for me.
