### ISSUE TITLE
Incorrect URL_REGEXP

### ISSUE THREAD

**Issue by giang-nghg** [bear/python-twitter#417]
In `twitter/api.py`, line 166:

`match = re.findall(URL_REGEXP, status)` does not work if there is a space or more before a URL (e.g. `re.findall(URL_REGEXP, 'some text http://someurl.com')` returns zero match)

I'm using version 3.2

**Comment by jeremylow** [comment]
I can't find the referenced code, but I think that's fixed in 3.2.1
