### ISSUE TITLE
Getting extended tweets

### ISSUE THREAD

**Issue by opb** [bear/python-twitter#420]
Hi there

Currently using v3.2

I'm using GetUserTimeLine and in some tweets I'm seeing `'truncated': true`. While you have some info in the docs about `tweet_mode` and `compat` vs `extended`, I couldn't see anywhere whether extended mode is actually supported, and if so, how to use it. Hopefully I'm just missing something!

Thanks

**Comment by jeremylow** [comment]
The Api has a `tweet_mode` param:

```python
api = twitter.Api(consumer_key=CONSUMER_KEY,
                  consumer_secret=CONSUMER_SECRET,
                  access_token_key=ACCESS_TOKEN_KEY,
                  access_token_secret=ACCESS_TOKEN_SECRET,
                  tweet_mode='extended')
```

I'll drop something in the docs for that. Thanks for the report!
