### ISSUE TITLE
URL_REGEXP in calc_expected_status_length looks not OK

### ISSUE THREAD

**Issue by belonesox** [bear/python-twitter#429]
When I use "verify_status_length=True" and  calc_expected_status_length
I see fails on
    replaced_chars = len(''.join(match))
because "match" is tuple.

See and run this sample https://gist.github.com/belonesox/aefe723ca5db36e5d819a53997041ba3

Probably URL_REGEXP is not OK

**Comment by jeremylow** [comment]
Sounds like you may be using an old version. That got cleaned up in https://github.com/bear/python-twitter/pull/416

If that's not the case, let me know.

**Comment by iainjames88** [comment]
When I `pip install python-twitter` the version installed from pypi has the bad code @belonesox mentioned. Is there going to be a newer version with the fix available on pypi?

**Comment by jeremylow** [comment]
@bear Can you upload the 3.2.1 to pypi?

**Comment by bear** [comment]
@iainjames88 @jeremylow  v3.2.1 has been uploaded to pypi
