### ISSUE TITLE
UpdateBanner: gifs don't work

### ISSUE THREAD

**Issue by Datamine** [bear/python-twitter#435]
I just ran into an issue with `Api.UpdateBanner`: I noticed that I could use the function to upload `.jpg` files seamlessly, but when I tried to upload `.gif` images, I got the following error:

`twitter.error.TwitterError: {'message': 'Image data could not be processed'}`

I'm wondering why this is the case. I tried it for two separate `.gif`s. On twitter, I can upload those files manually without a problem. I looked into `b64encode`, and also couldn't detect any issues there. 

----

Here is a gif for reference: [sample](http://netdna.webdesignerdepot.com/uploads/2008/11/sample-graphic.gif)

Update: converting any problematic gif to `.jpg` using ImageMagic allows you to upload the converted jpg.

**Comment by jeremylow** [comment]
I don't think that GIFs are supported on that endpoint, but the web client may be taking your GIF and converting it to JPEG/PNG. I'd try asking at https://twittercommunity.com, since that will probably be a better resource that trying to figure out what the remote server is doing.

**Comment by Datamine** [comment]
@jeremylow good call. I've opened a thread there: https://twittercommunity.com/t/update-profile-banner-doesnt-work-with-gifs/83288
