### ISSUE TITLE
Searching for an exact phrase 

### ISSUE THREAD

**Issue by ajama7** [bear/python-twitter#452]
Hi,

I am having the following issue. I want to search Twitter using the library to search for an exact phrase:

example 

results = api.GetSearch(
raw_query="l=&q=Adam%20Jama&count=1-")
print (results)

status(ID=838800113455742976, ScreenName=Adam_mdmph, Created=Mon Mar 06 17:15:05 +0000 2017, Text=u"RT @JAMA_current: Thomas Starzl, the 'father of transplantation,' has died at age 90. Read his 1990 JAMA review (Free PDF) \nhttps://t.co/tR\u2026"), Status(ID=838101371622735875, ScreenName=adam_greenblatt, Created=Sat Mar 04 18:58:32 +0000 2017, Text=u'RT @jennav5: Cannabinoids for Medical Use: A Systematic Review and Meta-analysis #NCBI #cannabis #JAMA https://t.co/a3DxJIWRww'), Status(ID=838074237567008769, ScreenName=adam_ald, Created=Sat Mar 04 17:10:43 +0000 2017, Text=u'RT @JAMA_current: Rembrandt reminds us that medicine, when practiced well, requires one to remain attentive to the pt\u2019s experience https://\u2026'), Status(ID=837385084223156225, ScreenName=AbooMeesham, Created=Thu Mar 02 19:32:16 +0000 2017, Text=u"HuKuRu KuRuN: Halorath: Sheikh @Ahmadhsameer  , Hasanath: Adam Husain (Hura), Noor: Husain Ahmed (Dharusalam), Jama'ath: Muhamad Ali (Ahiya)"), Status(ID=837381070253236224, ScreenName=AbooMeesham, Created=Thu Mar 02 19:16:19 +0000 2017, Text=u"HuKuRu KuRuN: Halorath: Hassan Sobah (Ahiya), Hasanath: Adam Husain (Hura), Nooru: Husain Ahmed (Dharusalam), Jama'ath: Muhammad Ali (Ahiya)")]

The result doesn't contain adam jama as an exact phrase.

However, when I do the following 

results = api.GetSearch(
raw_query="l=&q=Arsene%20Wenger&count=3")
print (results)

Status(ID=840244987405131776, ScreenName=SportsbookBTC, Created=Fri Mar 10 16:56:30 +0000 2017, Text=u"\ufffdbetbitcoin.proro When is the 'right time' for Arsene Wenger to decide his Arsenal future?\u2026 https://t.co/zSt7JUzrUA https://t.co/rAIuxXhwOZ"), Status(ID=840244894442651648, ScreenName=crizzlerizzle, Created=Fri Mar 10 16:56:08 +0000 2017, Text=u"RT @5_News: The kids at Lincoln's @StGilesacad have got a message for Arsene Wenger ahead of the FA Cup Quarter Final tomorrow. Stay tuned!\u2026")]

The query with Arsene Wenger does return the exact phrase. 
 
Please could someone shed some light on this issue please. Thanks.

**Comment by jeremylow** [comment]
You need to include the quotation marks for an exact search:

```python
results = api.GetSearch(raw_query="q=%22Adam%20Jama%22")
print(results)
```
That said, that search isn't returning anything at the moment. Your results may vary. (I can confirm that syntax is correct with `api.GetSearch(raw_query="q=%22Lebron%20James%22")`.)

**Comment by ajama7** [comment]
That clarifies that issues. Thanks. 

results = api.GetSearch(raw_query="q=%22Adam%20Jama%22since:2010-01-01 until:2017-03-11")
print(results)

Should return all results of Adam Jama between that period of time as it does in the twitter advanced search. 

Please could you shed light on this issues please. Thanks in advanced.

**Comment by jeremylow** [comment]
Yeah, twitter doesn't make full search available. See:

https://dev.twitter.com/rest/public/search

In particular:
> The Twitter Search API searches against a sampling of recent Tweets published in the past 7 days
