### ISSUE TITLE
how to Share a Tweet through Direct Messages

### ISSUE THREAD

**Issue by wu860** [bear/python-twitter#455]
how to Share a Tweet through Direct Messages

**Comment by jeremylow** [comment]
There's nothing special you have to do except include the tweet URL in the body of the direct message

**Comment by wu860** [comment]
share one  page to people via DM private. send url to someone ,there is only url. But Share the page to people .there is some webpage description. Cannot send DM to people to be some description? How ?

**Comment by jeremylow** [comment]
If I understand correctly, that's a matter of the client program (either Twitter's official app or something else) expanding the page's metadata. If you're sharing a tweet, that should get expanded in the official apps.

**Comment by wu860** [comment]
thank you
