### ISSUE TITLE
api.GetSearch does not take into account Count param

### ISSUE THREAD

**Issue by mikeres0** [bear/python-twitter#458]
Setting a `Count=X` parameter does not have any effect on the number of items returned by the API.

For example this call returns the default 15 items: 
`api.GetSearch(raw_query='q=to%3Amikeres0', result_type='popular', include_entities=True, count='100')`

**Comment by jeremylow** [comment]
If you use raw_query you need to specify the count in that. No other params
are honored. Check out the documentation for Searching, which should
clarify things.

-- 
Jeremy Low

**Comment by mikeres0** [comment]
Using the example below the API returns the specified count:
```results = api.GetSearch( raw_query="q=twitter%20&result_type=recent&since=2014-07-19&count=100")```

However the below still ignores the count param:
```tweets = api.GetSearch(raw_query="q=to%3A_mbservice%20&count=50")```

Do you have any idea why this would happen? 

Thanks

**Comment by jeremylow** [comment]
Couple of reasons:

1. It's not a high volume search;
2. Most of the results are older than 7 days;
3. Twitter's API search only searches a subset of the total volume of tweets;

Twitter wants you to use (and pay for) Gnip to access full search history. Check out this [page.](https://dev.twitter.com/rest/public/search). What's your use case? There may be a better way.

**Comment by mikeres0** [comment]
Gnip seems stupidly expensive for what I’m trying to achieve..

 

I’m trying to retrieve a list of tweets to run some analysis on them, it’s as simple as that.

**Comment by jeremylow** [comment]
Yeah, it's ridiculous. There are ways to get historical data:
https://github.com/sashaperigo/Trump-Tweets

I'd give that a shot. If you want to track and store incoming tweets, you
can use the streaming end points. I wrote a little thing about that

https://iseverythingstilltheworst.com/blog/2016/05/28/capturing_twitter_streams/

-- 
Jeremy Low

**Comment by mikeres0** [comment]
I'll take a look at your blog post, at first glance it looks helpful. 

Thanks for the help/advice @jeremylow 💯

**Comment by mikeres0** [comment]
> And that’s basically it at this point! If you don’t want to store all these tweets locally, you can set up a database and run this as a background service, but that’s another blog post.

Would be interested in hearing your thoughts on this!

**Comment by jeremylow** [comment]
Check out https://github.com/jeremylow/cyberpunkd.collector which uses either a Postgres database or an SQLite database to store the tweets. There's going to be some things there that you probably don't need (it was for an art project where users would take a photo of themselves at a specific location and tag it with a hashtag), but it'll give you an idea of how I set things up.
