### ISSUE TITLE
CreateFavorite raises set(['Uknown error: ']) for decode('utf-8')

### ISSUE THREAD

**Issue by maxpierini** [bear/python-twitter#461]
Sometimes (I can't really understand why and in which cases exactly, but when it happens for a user it lasts almost one day),
`api.CreateFavorite(status_id=ID)`
raises this error:
```
File "/usr/local/lib/python2.7/dist-packages/twitter/api.py", line 3390, in CreateFavorite
data = self._ParseAndCheckTwitter(resp.content.decode('utf-8'))
File "/usr/local/lib/python2.7/dist-packages/twitter/api.py", line 4860, in _ParseAndCheckTwitter
raise TwitterError({'Unknown error: {0}'.format(json_data)})
TwitterError: set(['Unknown error: '])
```

**Comment by jeremylow** [comment]
`POST` requests have a limit of 1,000/day, so if you try to fav too many tweets, that may be why you get the error. If it's happening to specific users, I'd try Twitter's support or post over on twittercommunity.com, which may be able to get you a better answer.
