### ISSUE TITLE
Pip and the Latest Release

### ISSUE THREAD

**Issue by penn5** [bear/python-twitter#472]
In my opinion the latest version is ready for release - at the very least do a "minor" version that fixes video uploads (this has been fixed in the master branch, but not 3.2.1 release)!

**Comment by jeremylow** [comment]
Yeah, I agree. I'll try to finish up the work on the collections endpoints this weekend and then maybe we can do a 3.3 release since we've had a few new features come through like App Only Auth. @bear what do you think?

**Comment by jursed** [comment]
Regarding pip, I'm somewhat confused about the current contents of python-twitter. Some functions which have been in the source for quite a long time seem to be absent in the pip package, for example Api.GetAppOnlyAuthToken [has been added](https://github.com/bear/python-twitter/commit/f2dd2d35a18428407017c6bbc1fe986c94e86fd0) in Dec 2016 and is [included in the docs](https://python-twitter.readthedocs.io/en/latest/twitter.html#twitter.api.Api.GetAppOnlyAuthToken), but is not included in the source tarball on PIP from Jan 2017. What am I missing? (Sorry for the OT.)

**Comment by bear** [comment]
@jeremylow - that makes a lot of sense, i've always enjoyed other libs that could get into a release cadence.

@jursed Not sure what that could be - most likely it's that I made a mistake with either the 2.* or 3.* release (i.e. I forgot to do one or the other)

**Comment by jeremylow** [comment]
@bear Sounds great to me! With the retirement of the streaming endpoints being announced, it's probably even more important as deprecations come and go.

@jursed I think it's just that we haven't done a release for a while.

**Comment by bear** [comment]
@jeremylow cool - after I get back from this work trip Sunday (and recover!) I will sync up with what needs to be in the next release and start that process.

**Comment by bear** [comment]
@jeremylow with the latest PRs and all that I am thinking of doing a release tonight - any thoughts?

**Comment by jeremylow** [comment]
Sounds good to me!

-- 
Jeremy Low

From: Mike Taylor <notifications@github.com> <notifications@github.com>
Reply: bear/python-twitter
<reply@reply.github.com>
<reply@reply.github.com>
Date: May 20, 2017 at 13:44:52
To: bear/python-twitter <python-twitter@noreply.github.com>
<python-twitter@noreply.github.com>
CC: Jeremy Low <jeremylow@gmail.com> <jeremylow@gmail.com>, Mention
<mention@noreply.github.com> <mention@noreply.github.com>
Subject:  Re: [bear/python-twitter] Pip and the Latest Release (#472)

@jeremylow <https://github.com/jeremylow> with the latest PRs and all that

**Comment by bear** [comment]
3.3 has been released
