### ISSUE TITLE
Rate limit and header changes 

### ISSUE THREAD

**Issue by jeremylow** [bear/python-twitter#475]
See here https://twittercommunity.com/t/upcoming-http-header-changes/86715 

May need to revisit rate limit code

**Comment by marccarre** [comment]
*If* the only change they make is indeed the casing of HTTP headers, given `python-twitter` is based on `requests` which uses a [`CaseInsensitiveDict`](https://github.com/kennethreitz/requests/blob/v2.14.2/requests/structures.py#L15) for HTTP headers, then there should be no work to do at all.

Indeed the only lines affected should be [these ones](https://github.com/bear/python-twitter/blob/master/twitter/api.py#L4982-L4984) and things should therefore "just work":

In the case of lowercased headers in the HTTP response:
```
>>> resp = requests.get('https://api.twitter.com/1.1/users/show.json?screen_name=%s' % screen_name, auth=auth)
>>> resp.headers
{[...], 'x-rate-limit-limit': '900', 'x-rate-limit-remaining': '899', [...]}
>>> resp.headers.get('X-Rate-Limit-Limit', 0)
'900'
>>> resp.headers.get('x-rate-limit-limit', 0)
'900'
```

In the case of mixed-cased headers in the HTTP response:
```
>>> resp = requests.get('https://httpbin.org/headers')
>>> resp.headers
{[...], 'Content-Type': 'application/json', [...]}
>>> resp.headers.get('content-type')
'application/json'
>>> resp.headers.get('Content-Type')
'application/json'
```
