### ISSUE TITLE
Tweets aren't returned by GetSearch

### ISSUE THREAD

**Issue by mblandfo** [bear/python-twitter#478]
I see many tweets here:

https://twitter.com/search?q=from%3Acityofmentor%20since%3A2017-04-01%20until%3A2017-04-20

This code returns 0 tweets:

```
api = twitter.Api(consumer_key=config["consumer_key"],
                consumer_secret=config["consumer_secret"],
                access_token_key=config["access_token_key"],
                access_token_secret=config["access_token_secret"],
                sleep_on_rate_limit=True,
                tweet_mode="extended")

q_string = "q=from%3Acityofmentor%20since%3A2017-04-01%20until%3A2017-04-20"
tweets = api.GetSearch(raw_query=q_string)
```

Note that if I change the month to 5 instead of 4, it does return tweets for 3 days, but still not the full date range specified like it would from the advanced search url

I also tried this code, but had the same problem:

```
startDate = "2017-04-01"
endDate = "2017-04-20"
api.GetSearch(term=user.screen_name, since=startDate, until=endDate) 
```

**Comment by mblandfo** [comment]
I'm still very interested in an answer to this, but I was able to workaround it using GetUserTimeline instead of GetSearch: https://github.com/mblandfo/python_twitter_utils/blob/master/get_users.py#L53

**Comment by jeremylow** [comment]
Unfortunately, the answer is that Twitter monetizes historical search results and sells that information through Gnip, which I'm told costs a fair amount of money to access. So through the GetSearch() method, you will only be able to access the previous seven days worth of tweets through that endpoint. 

My suggestion was going to be to do what you came up with, but that's often not an ideal solution if you're looking for tweets across user's timelines. That said, it's really the only work around at the moment. If you want to monitor tweets in real-time, then that's possible through the streaming endpoints, but search is always going to be limited to the last seven days.
