### ISSUE TITLE
GetUser/GetStatus id bug

### ISSUE THREAD

**Issue by taylornelson** [bear/python-twitter#481]
For some GetUser requests the id returned doesn't work correctly with GetStatus for example
aboveandbeyond:

data = (api.GetUser(screen_name='aboveandbeyond'))
print(api.GetStatus(data.id)) #returns an error

**Comment by jeremylow** [comment]
`data.id` in that case is the numeric ID of the twitter user 'aboveandbeyond'. `GetStatus` expects a status ID.
