### ISSUE TITLE
api.GetSearch method only returns two Status when there are many more on Twitter

### ISSUE THREAD

**Issue by jtara1** [bear/python-twitter#482]
My raw query and method call:
```
raw_query = "q=from%3ASmiteGame%20FWOTD"

self.statuses = api.GetSearch(raw_query=raw_query)
```

Statuses returned:
```
<class 'list'>: [Status(ID=873190710291431424, ScreenName=SmiteGame, Created=Fri Jun 09 14:51:03 +0000 2017, Text='Get Boosted! This weekend, complete a FWOTD to earn 3 Team Boosters!\n\nhttps://t.co/KRylCKb1AZ https://t.co/LjGRReHAib'), Status(ID=871849245774671874, ScreenName=SmiteGame, Created=Mon Jun 05 22:00:33 +0000 2017, Text="Don't be a loser - get a BOOSTER!\nThis weekend, complete a FWOTD to earn 3 Team Boosters!\n\nhttps://t.co/47TAbEAZsk https://t.co/lq1wLzyWaP")]
```

if we examine what twitter returns when manually searching, there are a lot more than 2 tweets.
https://twitter.com/search?q=from%3Asmitegame%20FWOTD

---

2nd question:

Would using the parameters, `until` and `since`, for the method call sort the tweets by the date they were tweeted?

edit: I added the parameter `result_type="recent"` to the `GetSearch` call, but it didn't seem to help any.

**Comment by jeremylow** [comment]
Please see https://github.com/bear/python-twitter/issues/478

**Comment by jtara1** [comment]
That'd be great if we could get the GetSearch docstring updated with this info.

**Comment by jeremylow** [comment]
Will do. I think a note in the online documentation would probably help too. Just been busy :(
