### ISSUE TITLE
Following specific IDs returns also tweets that mention them 

### ISSUE THREAD

**Issue by Maor-RZ** [bear/python-twitter#485]
Hi,

I assign a list of user's IDs to 'Follow' with the GetStreamFilter function.
The documentation says that I am only should get back tweets that were uploaded by those users & re-tweets of them - but in fact the stream contains also tweets which are only mentioning those users (e.g. tweets which contain @Boeing for the Boeing user's ID ). 

Is that supposed to happen? How can I prevent this from happening / filter the stream?

Thank you very much,
Maor

**Comment by jeremylow** [comment]
The documentation here: https://dev.twitter.com/streaming/overview/request-parameters#follow states that replies to a tracked user should be displayed, so I think this is what might be happening. If you want to filter out those tweets, try something like this:

```python
users_to_follow = [12,]

for tweet in api.GetUserStream(follow=users_to_follow):
    if tweet.user.id not in users_to_follow:
        pass
    else:
        # do something here with the tweet
```
