### ISSUE TITLE
Bug when differentiating text from URLs, causing an error for being over 140 chars

### ISSUE THREAD

**Issue by cdavid11** [bear/python-twitter#489]
I was having the darndest time figuring out why I was getting an error about being over the 140 character limit. It turns out, some of the text was being recognized as a URL.

I was trying to tweet this line:

`#DonaldTrump has signed: S.84 - A bill to provide for an exception to a limitation against appointment of persons...https://www.whitehouse.gov/legislation/s84-bill-provide-exception-limitation-against-appointment-persons-secretary-defense`

It's turns out that I had a couple of issues with this.
Take a look at this:

`#DonaldTrump False 12
has False 3
signed: False 7
S.84 True 23
- False 1
A False 1
bill False 4
to False 2
provide False 7
for False 3
an False 2
exception False 9
to False 2
a False 1
limitation False 10
against False 7
appointment False 11
of False 2
persons...https://www.whitehouse.gov/legislation/s84-bill-provide-exception-limitation-against-appointment-persons-secretary-defense True 23`

persons... is being considered a part of the URL and the name of the S.82 in the name is also being recognized as a link. This is causing the error. My current workaround is setting the length check to false like so:

`status = api.PostUpdate(to_tweet, verify_status_length=False)`

So I just wanted to open up this issue for it! Thanks.

**Comment by jeremylow** [comment]
Fixed in 65f8411
