### ISSUE TITLE
GetSearch only returning 15 results regardless of count setting

### ISSUE THREAD

**Issue by WolfHoward** [bear/python-twitter#495]
I'm using GetSearch to identify users tweeting about specific hash tags. This is my code:

```
import twitter
from api_access import api_info

api = twitter.Api(consumer_key=api_info['consumer_key'],
                consumer_secret=api_info['consumer_secret'],
                access_token_key=api_info['access_token_key'],
                access_token_secret=api_info['access_token_secret'])

search = api.GetSearch(raw_query='q=%23aging', count=100, result_type="mixed")
```

I've tried it with various counts and I still only get 15 results. I thought it might have been the sleep_on_rate_limit setting, but I tried with that set to False and get the same result.

**Comment by WolfHoward** [comment]
Also tried with result_type set to "mixed" even though it's the default and "popular", no effect.

**Comment by jeremylow** [comment]
`raw_query` overrides every other parameter, so you'll need to specify the `count` as part of the query string. See: https://python-twitter.readthedocs.io/en/latest/searching.html
