### ISSUE TITLE
"Connections" don't work properly (bug, how to solve it)

### ISSUE THREAD

**Issue by jmlipman** [bear/python-twitter#497]
I made a simple script in which I retrieve users by using LookupFriendship and when I access to each individual user.connections["followed_by"] I realized that all of them were following me back (which is not true).

I spot 2 problems/bugs in the code.

1) The first problem is related to its design: in the class UserStatus we have  a dictionary "connections" and "param_defaults" that share some attributes which is redundant and confusing. I realized that my code worked if I check user.followed_by instead of user.connections["followed_by"]. It makes no sense to have these two attributes while one of them doesn't work.

2) But then, why did I see that all my friends followed me back? The answer is because the dictionary "connections" was outside the `__init__` so once the attributed "followed_by" is detected (as True) all of the elements will share the same value. I'm not really sure why because I thought they were completely independently different objects, as they are generated as: [UserStatus.NewFromJsonDict(x) for x in data].

Solutions:
A) Delete and forget about the dictionary "connections".
B) Move the dictionary "connections" inside the `__init__` so every time it's called they will all be initialized as False.

JM.

**Comment by jeremylow** [comment]
Hey, thanks for the report.

1. `UserStatus.connections` is used to hold the default connections for use in the `UserStatus.__repr__()` function and parsing `kwargs` in `UserStatus.__init__()`.
2. This is an attribute of how python deals with class variables.

a. Perhaps it could be a private class variable, which would make its function a little clearer, but it's working as intended. The truth or falsity of the items in the dictionary isn't meant to be descriptive as to the the specific UserStatus instance.
b. That would be redundant with the other class attributes and obviated by a., above. The idea behind the way it's structured is that end users can dot access the specific attributes without having to perform a dictionary lookup.

Does that address your concerns?

**Comment by jmlipman** [comment]
That makes sense ; )
