### ISSUE TITLE
Issue with calculating expected status length

### ISSUE THREAD

**Issue by Michels10** [bear/python-twitter#500]
I'm not sure if this should be considered a bug or if this is the intended functionality, so I figured I'd open a ticket to see what the thoughts are...

Currently the Twitter docs at https://dev.twitter.com/basics/tco state: 

> If you are not using the opt-in features, only links shorter in length than a t.co URL will be wrapped by t.co. All links t.co-length or longer should be considered as t.co’s maximum length. For example, if help/configuration reports 20 characters as the maximum length, and a user posts a link that is 125 characters long, it should be considered as 20 characters long instead. If they post a link that is 18 characters long, it’s still only 18 characters long.

> If you are using the opt-in features, all URLs regardless of length should be considered to be the maximum length reported to you by help/configuration.

How do we determine if we're using the opt-in features?  Presently it would appear that my tweets with shortened urls (bit.ly) are being POSTed at 21 characters, and not being wrapped at all by t.co.  If this is the correct functionality, can we modify the ```calc_expected_status_length``` function to be something like the following?

```
def calc_expected_status_length(status, short_url_length=23):
    status_length = 0
    for word in re.split(r'\s', status):
        if is_url(word):
            status_length += short_url_length if len(word) >= short_url_length else len(word)
        else:
            status_length += len(word)
    status_length += len(re.findall(r'\s', status))
    return status_length
```

**Comment by jeremylow** [comment]
Opt-in features are only supported through the Gnip data at the moment, which we don't support. The t.co links are presently enabled for all links included in a status and take up the reserved `short_url_length`.
