### ISSUE TITLE
URL entity unwound.url

### ISSUE THREAD

**Issue by sa-matiny** [bear/python-twitter#515]
Hi, 
Twitter api has features for url entity to Expanded URL Data. It says using url.unwound will show url features like it's title and features. but your library does not support this feature.
Here is twitter api link about this features:
[https://developer.twitter.com/en/docs/tweets/enrichments/overview/expanded-and-enhanced-urls](url)

**Comment by jeremylow** [comment]
This is only available through the Gnip service, which python-twitter doesn't support (it would be prohibitively expensive to do so).

http://support.gnip.com/enrichments/expanded_urls.html
