### ISSUE TITLE
What plans on date of release version 3.3.1?

### ISSUE THREAD

**Issue by mnvx** [bear/python-twitter#516]
Thanks for great library! Im interested in release of bug fixes situated currenctly in master branch.

**Comment by 9b** [comment]
Bumping to understand if this release was missed. Pypi is still showing 3.3 despite documentation referencing 3.3.1.

**Comment by jeremylow** [comment]
@bear can we get an update on pypi?

**Comment by 9b** [comment]
@jeremylow are you able to cut releases?

**Comment by jeremylow** [comment]
@9b unfortunately I can't, sorry about that.

**Comment by jyee** [comment]
+1 to this. 3.3 is nearing the 9 month mark with tons of improvements in master since it was released. Tagging a new release would be welcome.

**Comment by robcresswell** [comment]
@bear Anything we can do to help? I don't like to make demands without offering to do something to aid the process. Could you delegate the release process to someone else perhaps?

**Comment by family-guy** [comment]
ditto above. updating this would be great!

**Comment by jeremylow** [comment]
We'll have a release this weekend. Sorry about the long wait time for this one, folks. Thanks for sticking around!

**Comment by vEpiphyte** [comment]
Thanks for the update!

**Comment by jeremylow** [comment]
New release is on pypi as version 3.4 (there were some deprecations which we'd planned but didn't get out before packaging 3.3).
