### ISSUE TITLE
`GetSearch` method doesn't return data about limit headers

### ISSUE THREAD

**Issue by eranhirs** [bear/python-twitter#517]
When using `GetSearch` there are some interesting HTTP headers about the remaining limit for your requests, as documented [here](https://developer.twitter.com/en/docs/basics/rate-limiting).

It would be very useful to have access to this information.

**Comment by jeremylow** [comment]
That information gets copied over to the RateLimit instance for a given API: https://github.com/bear/python-twitter/blob/master/twitter/ratelimit.py

**Comment by eranhirs** [comment]
I am not sure I follow.
In `GetSearch` I don't see the headers copied, looking [at this file](https://github.com/bear/python-twitter/blob/8c5a036ef5c10f291d6affeb13878d5e1987f9fe/twitter/api.py).
Also, `ratelimit.get_limit` seems to make a http request to get the limits.

**Comment by jeremylow** [comment]
The information gets copied over to `api.rate_limit` each time a call is made to `api._RequestUrl()` here: 

https://github.com/bear/python-twitter/blob/8c5a036ef5c10f291d6affeb13878d5e1987f9fe/twitter/api.py#L5067

**Comment by eranhirs** [comment]
Thank you 👍
