### ISSUE TITLE
Cannot download using command pip install python-twitter. Receive could not fetch URL error

### ISSUE THREAD

**Issue by scday** [bear/python-twitter#518]
Could not fetch URL https://pypi.python.org/simple/python-twitter/: There was a problem confirming the ssl certificate: [Errno 1] _ssl.c:504: error:0D0890A1:asn1 encoding routines:ASN1_verify:unknown message digest algorithm - skipping
  Could not find a version that satisfies the requirement python-twitter (from versions: )
No matching distribution found for python-twitter

**Comment by jeremylow** [comment]
This looks like a problem with either pypi or your system configuration. I was able to install from pypi this morning using 2.7.
