### ISSUE TITLE
Work around guess_type() bug with query strings.

### ISSUE THREAD

**Issue by dgilman** [bear/python-twitter#520]
In parse_media_file() a HTTP url gets fed through basename to get the "filename" and then passed to mimetypes.guess_type() to guess what the MIME type is based on the extension of the file. If your file has a query string guess_type() can't figure out the MIME type and returns None. This gets passed up to Twitter which ends up returning an error 'media type unrecognized'.

In some cases you can strip the query string/fragment with urlparse and hand that to python-twitter which will let it work properly. But what about URLs that *require* a query string to work? If you take it off yourself it'll guess the MIME type right but http_to_file() will fail as it's returning bad content. 

As a solution guess_type() should strip query strings before passing the URL to basename on line 218 in twitter_utils.py. The URL should be passed to http_to_file without change.

**Comment by jeremylow** [comment]
fix lands in https://github.com/bear/python-twitter/commit/9a0796072d629c2f96d5e8dd69b837bcd1614a82
