### ISSUE TITLE
Use proper API in http_to_file

### ISSUE THREAD

**Issue by dgilman** [bear/python-twitter#521]
http_to_file() in twitter_utils.py gets data out of the Response object as Response.raw.data which is a property from the underlying urllib3 library that doesn't do the proper decoding.  If the server sent gzipped data it won't be decompressed. Response.content should be used instead as it handles the decoding for you (see https://github.com/requests/requests/blob/master/requests/models.py#L724 , decode_content=True)

**Comment by jeremylow** [comment]
Fixed in 2bf461ffdf276d05c6d0933621cddfacd02bf204

Thanks!
