### ISSUE TITLE
Character limit from 140 to 280 ?

### ISSUE THREAD

**Issue by vaibhavmathur91** [bear/python-twitter#524]
word limit should be changed from 140 to 280 ??
in twitter/api.py file

**Comment by trevorprater** [comment]
I submitted a [PR](https://github.com/bear/python-twitter/pull/525) that fixes this issue.

**Comment by nahratzah** [comment]
For what it's worth, constructing ``twitter.Api`` with ``tweet_mode='extended'`` works for me.

It changes the text field name of a status from ``text`` to ``full_text``.

**Comment by csabatini** [comment]
> For what it's worth, constructing twitter.Api with tweet_mode='extended' works for me.
Was about to say the same, this seems to capture the >140 tweets as full_text

**Comment by foozmeat** [comment]
I'm trying to post 280 chars and I'm receiving the following:

` [{'code': 186, 'message': 'Status is over 140 characters.'}]`

even though my account can otherwise post 280 chars on the website.

**Comment by trevorprater** [comment]
If you switch to my branch, you can post 280 chars.

https://github.com/bear/python-twitter/pull/525

**Comment by foozmeat** [comment]
@trevorprater thanks, I looked over your changes and I don't think they'll help me. I'm already passing `verify_status_length=False` so the length check is skipped. My post is being rejected by twitter which makes me think the api call needs to change in some way.

**Comment by Cakeofdestiny** [comment]
@nahratzah Oddly that doesn't work for me, even when using the full_text attribute. Thanks for the tip anyway :D

**Comment by jeremylow** [comment]
Lands with #525
