### ISSUE TITLE
“tweepy.error.TweepError: Twitter error response: status code = 429” 

### ISSUE THREAD

**Issue by varun4github** [bear/python-twitter#526]
I am trying to make an application and getting error “tweepy.error.TweepError: Twitter error response: status code = 429” . I have read about rate limit on twitter , but have seen many web application which are making much more requests that what I am trying to make . 

Thank you .

**Comment by jeremylow** [comment]
This is for a different library. You're looking for https://github.com/tweepy/tweepy
