### ISSUE TITLE
Limit exceeded calling getFollowers

### ISSUE THREAD

**Issue by arkkanoid** [bear/python-twitter#530]
Hi, 
I'm using this library to make different calls. When I do this call:
api.GetFollowers(screen_name='facebook')
I get:
witter.error.TwitterError: [{u'message': u'Rate limit exceeded', u'code': 88}]

Using any other request it works as expected:
api.GetUser(screen_name='facebook')
User(ID=2425151, ScreenName=facebook)

Someone has the same issue?

**Comment by jeremylow** [comment]
With high follower accounts, you should use `api.GetFollowerIDsPaged` or instantiate the api instance with `sleep_on_rate_limit=True` or manually page through the followers.

The GetFollowers method attempts to retrieve all followers of a given user, so it'll hit the rate limit if you try to get the followers of an account like Facebook.
