### ISSUE TITLE
Quick question regarding favorites and RT's of a tweet

### ISSUE THREAD

**Issue by zefoo** [bear/python-twitter#532]
From my research, there is not a way to see user IDs that favorited a tweet, or user IDs of people who RT'd a tweet, if I have a tweet status. Can someone confirm this? 

The only option would be scraping the website, which violates ToS, and likely doesn't even return all results. (I don't plan on going this far)

Thank you.

**Comment by zefoo** [comment]
... it looks like I can get RT's of a status with GetRetweeters(status_id, cursor=None, count=100, stringify_ids=False), but the max is 100 users. And only 100, despite setting cursor to anything else. I've tried to change the cursor but the results are always the same.

**Comment by jeremylow** [comment]
Yeah you can't get the users that favorited a tweet, but you can get RTs. That said, you're correct - you can only get 100 RTs: https://github.com/bear/python-twitter/issues/306

**Comment by zefoo** [comment]
Thank you @jeremylow! Quick question: do you happen to know how the 100s RTs are ordered? eg. does the RTs show the first 100, or does it show the last 100? I'm thinking, if I can re-crawl a status every few hours and always pull the newest 100 RTs (if there are more than 100)... I could make that work. 

From my tests, the results don't seem consistent – but I may be reading the data incorrectly and want to be sure. 

Thank you!
