### ISSUE TITLE
UsersLookup Splits `screen_name` by Characters When Passed a str

### ISSUE THREAD

**Issue by caleblogan** [bear/python-twitter#535]
When passing UsersLookup `screen_name='foouser'`,  screen_name will get turned into `'f,o,o,u,s,e,r'`.
It looks like `screen_name` can be a string by looking at the first part of the following:
`screen_name (str, optional):
A list of screen_names to retrieve extended information.` 

LookupFriendship does type checking on `screen_name` to determine if its a tuple, list, User, or str.

**Comment by jeremylow** [comment]
Changed in 49c265d459cc31006370f6e8e14f11715982eeee
