### ISSUE TITLE
Throttle or wait for API error?

### ISSUE THREAD

**Issue by zefoo** [bear/python-twitter#536]
Currently, my code waits for Twitter to say I've exceeded max API requests within a window then it sleeps for 15 minutes (I do this on my end, not using python-twitter). I'm wondering, is this ok? Or does Twitter ban an "aggressive" script (even if it sleeps for 15 minutes upon first request that throws an error?) 

I could build in more logic to prevent my script from ever getting an error from Twitter, but if it's fine as-is I'll leave it. I mostly want to make sure the app doesn't get blocked or anything like that. Curious what you've all seen in your experience. I bet it's fine as-is. Thank you –

**Comment by jeremylow** [comment]
I've never seen a ban from being overly aggressive in terms of rate-limiting, but I suppose it does happen. I would expect that this behavior is fine as-is.
