### ISSUE TITLE
140 character error even in tweet_mode=extended 

### ISSUE THREAD

**Issue by focusaurus** [bear/python-twitter#539]
I have code to tweet via PostUpdate:

```py
    api = twitter.Api(
        consumer_key=conf["twitter"]["consumer_key"],
        consumer_secret=conf["twitter"]["consumer_secret"],
        access_token_key=key,
        access_token_secret=secret,
        tweet_mode="extended")
    try:
        print(api.PostUpdate(message).text)
    except twitter.TwitterError as info:
        print("ERROR:", info)
```

It prints `ERROR: Text must be less than or equal to 140 characters.`. I was hoping `tweet_mode=extended` would fix this but it seems not. I expect to be able to post tweets up to 280 chars, which I can do via the twitter web site.

**Comment by philgyford** [comment]
Annoying isn't it. I got round it for now by using [the most recent commit](https://github.com/bear/python-twitter/commit/c736c47368c69a60c140546a37e25332c15dbbbf) on `master`, in case this helps you:

`git+git://github.com/bear/python-twitter.git@c736c47368c69a60c140546a37e25332c15dbbbf`

**Comment by jeremylow** [comment]
This will be resolved in the next release.
