### ISSUE TITLE
"L.512+MVG" is a URL?

### ISSUE THREAD

**Issue by d3d9** [bear/python-twitter#541]
The beginning of the tweet looks like this: "Sperrung der Selbeckerstr L.512+MVG Linie 84".
The estimated character count is too high because "L.512+MVG" is seen as a URL requiring 23 characters.
This ended up giving me an error because the overall tweet length was too much.

I tried some other strings, it seems like `(any string containing an alphabetic character and not starting with a dot)+"."+(any string starting with a number)` is seen as a URL.

**Comment by jeremylow** [comment]
Fixed in 65f8411972b148b496a37089566a7896eea21b0f
