### ISSUE TITLE
PostUpdate broken on python 2.7 when using str (byte) message

### ISSUE THREAD

**Issue by h3llrais3r** [bear/python-twitter#546]
Hi, I've just upgraded to the last version 3.4 but I'm encountering the following issue:
I cannot longer do a PostUpdate in Python 2.7 when the message is a str(byte) string.
When using a unicode string, it works.

```
api = Api(consumer_key=CONSUMER_KEY,
          consumer_secret=CONSUMER_SECRET,
          access_token_key=TWITTERKEY,
          access_token_secret=TWITTERSECRET)

api.PostUpdate(message[:280])
```

I assume that you want to work with unicode string internally, but the code below does not seem to convert a byte string to a unicode string in all cases.

![image](https://user-images.githubusercontent.com/1945295/36450089-24aaf56c-168d-11e8-8470-3aeabdee6e74.png)

It seems that https://github.com/bear/python-twitter/blob/master/twitter/api.py#L1106-L1109 is only for Python 3 (where `str` is unicode). In Python 2 this is a byte string.
You may want to use the `six` library here to support both Python 2 and 3.

Since there is no conversion to unicode, it results in the following error:
````
File "C:\Tools\GitHub\Auto-Subliminal\lib\twitter\api.py", line 1111, in PostUpdate
    if verify_status_length and calc_expected_status_length(u_status) > CHARACTER_LIMIT:
  File "C:\Tools\GitHub\Auto-Subliminal\lib\twitter\twitter_utils.py", line 185, in calc_expected_status_length
    if any([ord(normalize("NFC", character)) in char_range for char_range in CHAR_RANGES]):
TypeError: must be unicode, not str
```

**Comment by jeremylow** [comment]
fixed in 409a7335f59dc4570c5d60065e7195f58285d9d0
