### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by chasen-bettinger** [bear/python-twitter#548]
I am receiving an error after searching for the hashtag 'Pink Ribbon'.

Here is the error: 

`Traceback (most recent call last):
  File "c:\Users\betti\Desktop\pink-ribbon\pink-ribbon\twitter-analysis.py", line 12, in <module>
    print(tweet.text)
  File "C:\Users\betti\AppData\Local\Programs\Python\Python36-32\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 12-45: character maps to <undefined>
`

Here is my code:

```
response = api.GetSearch(term="PinkRibbon") 

for tweet in response:
    print(tweet.text)
```

Version of python: Python 3.6.4
Operating System: Windows 10

I have tried .unicode("utf-8") along with other things and have no luck - my code still isn't working. I think a correction was attempted in #330 but I am still receiving this error.

**Comment by jeremylow** [comment]
do you know the id of the tweet that's causing the problem so i can test against it?

**Comment by chasen-bettinger** [comment]
@jeremylow 968858734666514432

![image](https://user-images.githubusercontent.com/24480592/36811524-1c674954-1c9c-11e8-970b-005cba2810c1.png)

**Comment by jeremylow** [comment]
weird. 

can't seem to reproduce the error on linux. do you have the file encoding for `twitter-analysis.py` set to utf8? what's the terminal you're using?

**Comment by chasen-bettinger** [comment]
@jeremylow I think this is a [visual studio code problem](https://github.com/Microsoft/vscode/issues/32769). Thank you for your quick response. After using the terminal and not code runner I got output.

**Comment by jeremylow** [comment]
Ok, good luck - sorry to hear that; hope it gets fixed soon.
