### ISSUE TITLE
Documentation: Error in UsersLookup

### ISSUE THREAD

**Issue by skilfullycurled** [bear/python-twitter#549]
Documentation for [UsersLookup](https://python-twitter.readthedocs.io/en/latest/twitter.html#twitter.api.Api.UsersLookup) states:

```
user_id (int, list, optional) – A list of user_ids to retrieve extended information. 
screen_name (str, optional) – A list of screen_names to retrieve extended information.
```

However, I think both the user_id and screen_name parameters need to be lists.

```
user_id (int, list, optional) – A list of user_ids to retrieve extended information. 
screen_name (str, list, optional) – A list of screen_names to retrieve extended information.
```

I think the API may have once been a long comma separated string, but that doesn't appear to be working for me where as a list of strings does.

**Comment by jeremylow** [comment]
This was just recently changed. It should work for strings and lists. Thanks for catching that.

**Comment by skilfullycurled** [comment]
No problem!

Do you mean it should work with a string of a single username or a list of usernames, or that it should also work for a string of usernames ('user_one,user_two,user_three,...'?)  When I try the latter, it splits the string into letters and returns the Users who have accounts for the unique set of letters ('e', 'h', ',', 'o', 'n', 's', 'r', 'u', 't', 'w', '_').

**Comment by jeremylow** [comment]
It should work with both in the next release on pypi. Its in master right now.

**Comment by skilfullycurled** [comment]
Ahhhhhhhhh.  I see now.  Thanks!
