### ISSUE TITLE
make dev fails with OpenSSL 1.1: please bump Makefile Python 2.7 version to at least 2.7.13

### ISSUE THREAD

**Issue by jeromecc** [bear/python-twitter#555]
Hi!
 * Debian 9 is using OpenSSL 1.1.0.
 * OpenSSL 1.1.0 support in the ssl module was only added to Python 2.7.13, 3.5.3 and 3.6.0

On Debian Stable and Testing, make dev cannot build Python 2.7.11

Is it possible to set the version to at least 2.7.12? It will make contributions easier for users of recent GNU/Linux distros. Thanks!

See https://github.com/pyenv/pyenv/issues/945

**Comment by jeremylow** [comment]
Sure, makes sense. Thanks for the report.

**Comment by jeremylow** [comment]
Fixed in #563
