### ISSUE TITLE
Is there any way to get over 140 character text response from GetHomeTimeline?

### ISSUE THREAD

**Issue by yell0wu** [bear/python-twitter#558]
Excuse me if this is the wrong place to ask, I'm new to github.

With twitter's changes to support statuses over 140 characters, is there any way to get the untruncated version of a status using GetHomeTimeline?

`
a = api.GetHomeTimeline(contributor_details=True)    
`
`
home_timeline= [i.text for i in a]
`

The text returned from this is truncated to 140 characters, cutting off the rest.

**Comment by jeremylow** [comment]
The API will need to be created with `tweet_mode=extended` and then you'll have a `full_text` attribute on tweets:

```python
api = twitter.Api(
    CONSUMER_KEY,
    CONSUMER_SECRET,
    ACCESS_TOKEN,
    ACCESS_SECRET,
    tweet_mode="extended")
a = api.GetHomeTimeline(contributor_details=True)
home_timeline= [i.full_text for i in a]
```

**Comment by yell0wu** [comment]
```python
api = twitter.Api(
    CONSUMER_KEY,
    CONSUMER_SECRET,
    ACCESS_TOKEN,
    ACCESS_SECRET,
    tweet_mode="extended")
a = api.GetHomeTimeline(contributor_details=True)
home_timeline= [i.full_text for i in a]

#printing second tweet full_text
print(home_timeline[1])

```

returns this:
![alt text][logo]

[logo]: https://i.imgur.com/T6Y24gZ.png "output"

which is 140 characters:
![alt text][pogo]

[pogo]: https://i.imgur.com/6RyK6kw.png "140 characters!!"

with the full text here:
![alt text][rogo]

[rogo]: https://i.imgur.com/sYHEBBT.png "full tweet"

It seems to be an issue with retweets not showing the full text while non-retweets do show the full text. Is there a way around retweets not showing fully?

**Comment by csabatini** [comment]
@yell0wu Did you ever solve the truncated retweets problem?  I am seeing the same thing. Normal tweets are okay.
