### ISSUE TITLE
Is there a documented, standard way of checking for an error code when TwitterError is raised?

### ISSUE THREAD

**Issue by nachogoro** [bear/python-twitter#569]
I managed to write code that seems to work in order to check Twitter's error code when catching a `TwitterError`. I am not sure if this is the right way of doing it (maybe it can be done with less checking) and if it could fail with certain `TwitterError`s (e.g. because not all the raised `TwitterError`s use a list as a message):

```
        try:
            return api.GetSearch(query)
        except twitter.error.TwitterError as e:
            # Check whether it was a rate-limit-exceeded error
            if (isinstance(e.message[0], dict)
                    and 'code' in e.message[0]
                    and e.message[0]['code'] == 88):
                print('Exceeded rate limit!)
```

I find the code tedious to write, and unintuitive (it took me a bit to realise `TwitterError.message` is not a `str`, but a `list` with the first element being a `dict`, at least for the exception I was getting). I could not find anything about this in the official documentation, so I'd like to know if there is an easier way. It is also a request to document this in the official `readthedocs` if it is not already.

**Comment by jeremylow** [comment]
```python
except twitter.TwitterError as e:
    if '88' in repr(e):
        print('Exceeded rate limit!)
```

**Comment by nachogoro** [comment]
Thanks for the reply, Jeremy. However, isn't it possible that other error code will contain in the future the characters '88' without it being the error code 88 (e.g. 288 or 881)? Or that the number somehow shows in the error message but is not the actual error code? How about the `TwitterError` not having an error code at all but its message happens to have these two characters (or characters conforming any of the other error codes)?

Since the error code seems to be part of a dictionary, I thought there would be a supported way of accessing that dictionary for any `TwitterError` raised.

**Comment by jeremylow** [comment]
No, you can check here for the list of error codes: https://developer.twitter.com/en/docs/basics/response-codes.html

Other than that, there's really no standard way of doing it.
