### ISSUE TITLE
Oauth not working: NameError: name '$mykey' is not defined

### ISSUE THREAD

**Issue by improvethings** [bear/python-twitter#575]
>>> api = twitter.Api(consumer_key=[$mykey],
...                   consumer_secret=[hfsjdkfhjdf],
...                   access_token_key=[1234-fjkdsfjsdsdf],
...                   access_token_secret=[fsdfhjdks])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name '$mykey' is not defined # obviously I've removed my key and replaced it here with $mykey so as to not share my key with all you folks. Same issue with the helper script:

$ python get_access_token.py 
Enter your consumer key: $mykey
Traceback (most recent call last):
  File "get_access_token.py", line 77, in <module>
    main()
  File "get_access_token.py", line 71, in main
    consumer_key = input('Enter your consumer key: ')
  File "<string>", line 1, in <module>
NameError: name '$mykey' is not defined

**Comment by jeremylow** [comment]
What’s the version of the library you’re using and the python version?

**Comment by improvethings** [comment]
$ python -V 
Python 2.7.13
# default on Debian 9
$ python -c "import twitter; print(twitter.__version__)"
3.4.2

**Comment by jeremylow** [comment]
Updated the `get_access_token.py` script to work across python 2 and 3. Give it a shot and let me know if that fixes your issue. Also take a look at the `examples/` folder to see if anything there gives you a clue as to what's going wrong.

**Comment by improvethings** [comment]
Thanks! That worked. I'm not sure if these logs are relevant: 

Enter your pincode? Fontconfig warning: "/etc/fonts/fonts.conf", line 160: blank doesn't take any effect anymore. please remove it from your fonts.conf
[32050:32059:0706/104632.836535:ERROR:nss_util.cc(724)] After loading Root Certs, loaded==false: NSS error code: -8018
ATTENTION: default value of option force_s3tc_enable overridden by environment.
[32050:32244:0706/104633.778256:ERROR:connection.cc(1888)] Web sqlite error 5, errno 0: database is locked, sql: PRAGMA auto_vacuum
[32050:32244:0706/104633.778343:ERROR:connection.cc(1888)] Web sqlite error 5, errno 0: database is locked, sql: PRAGMA journal_mode = TRUNCATE
0342356

Generating and signing request for an access token...

Your tokens/keys are as follows:
[deleted]

As an aside, for some reason my view_friends.py had
ACCESS_TOKEN_KEY = 'XXXXXX'
access_token_key=ACCESS_TOKEN
when it should have been access_token_key=ACCESS_TOKEN_KEY. I'm not sure why my few day old git pull has files that appear to be over 2 years old...

**Comment by jeremylow** [comment]
Weird. Well, I'm glad that solved it for you. As for those logs: those are from you system it looks like. Nothing from python-twitter would generate something like that.
