### ISSUE TITLE
How to get URL of tweet?

### ISSUE THREAD

**Issue by Endogen** [bear/python-twitter#585]
I'm using `api.GetUserTimeline` but i don't see any way to get the URL of the returned `Status` items?

EDIT: I mean the URL to the actual Tweet on Twitter

**Comment by Endogen** [comment]
Really no answer to that?

**Comment by jeremylow** [comment]
It’s 

```
twitter.com/{username}/status/{status_id}
```

Please give people more time to respond. This is free software and we’re all volunteers. 

Jeremy Low

**Comment by Endogen** [comment]
That's what i initially thought but then kind of dismissed it - no idea why. Thank you for that, works! And sorry for the impatience, you are of course right.
