### ISSUE TITLE
Status.text only returns 140 characters

### ISSUE THREAD

**Issue by SamelCamel** [bear/python-twitter#586]
Whenever I get tweets using `GetUserTimeline`, the returned tweets' `text` attribute only contains the first 140 characters, plus an ellipsis character (...). Is there a way to get the complete tweet if it's over 140 characters?

**Comment by jeremylow** [comment]
You have to instantiate the API with `tweet_mode='extended'` and then `Status().full_text` should have the data you need.

**Comment by sarthak-m** [comment]
I'm getting this error: `GetUserTimeline() got an unexpected keyword argument 'tweet_mode'`
