### ISSUE TITLE
`twitter.error.TwitterError: [{'message': 'Sorry, that page does not exist.', 'code': 34}]` while trying to get direct messages

### ISSUE THREAD

**Issue by bastbnl** [bear/python-twitter#592]
I'm getting a `twitter.error.TwitterError: [{'code': 34, 'message': 'Sorry, that page does not exist'}]` on python 3.5 using `python-twitter==3.5.0`. I've been reading through an older issue #587 and that doesn't seem to work properly.

`Api.GetDirectMessages` uses  `url = '%s/direct_messages.json' % self.base_url` (https://github.com/bear/python-twitter/blob/v3.5/twitter/api.py#L2920), which appears to be the old url. 

I changed it to `url = '%s/direct_messages/events/list.json' % self.base_url` and now run into this:
```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/var/www/brownpapersession/alpha/brownpapersession/various/tweet.py", line 62, in get_direct_messages
    messages = twitter.GetDirectMessages()
  File "/var/www/brownpapersession/alpha/env/lib/python3.5/site-packages/twitter/api.py", line 2943, in GetDirectMessages
    return [DirectMessage.NewFromJsonDict(x) for x in data]
  File "/var/www/brownpapersession/alpha/env/lib/python3.5/site-packages/twitter/api.py", line 2943, in <listcomp>
    return [DirectMessage.NewFromJsonDict(x) for x in data]
  File "/var/www/brownpapersession/alpha/env/lib/python3.5/site-packages/twitter/models.py", line 88, in NewFromJsonDict
    json_data = data.copy()
AttributeError: 'str' object has no attribute 'copy'
```

**Comment by bastbnl** [comment]
Deleting a message via the same API appears to fail as well:
`twitter.DestroyDirectMessage()` raises `twitter.error.TwitterError: [{'message': 'Sorry, that page does not exist.', 'code': 34}]`

**Comment by mazjindeel** [comment]
I am encountering this issue as well, for `send_direct_message`.

**Comment by mahaeraudee** [comment]
i have same problem with python 3.7
is there any solution ?
is it work with old python version anyone test?

**Comment by jeremylow** [comment]
That endpoint was deprecated. It’s not your python version. We’ll be working on implementing support for the new endpoints shortly.

**Comment by gabriele99g** [comment]
The issue is still present. (twitter-python version: 3.5)

**Comment by PokestarFan** [comment]
The issue is still very present as can be seen by my thread in Feb. 2 that still hasn't done anything.

**Comment by PokestarFan** [comment]
Anyone that needs a quick fix can go to [this comment](https://github.com/bear/python-twitter/issues/603#issuecomment-463030438)

**Comment by chrischma** [comment]
> That endpoint was deprecated. It’s not your python version. We’ll be working on implementing support for the new endpoints shortly.

any news?

**Comment by PythonCoderAS** [comment]
> > That endpoint was deprecated. It’s not your python version. We’ll be working on implementing support for the new endpoints shortly.
> 
> any news?

use a different API, this one is basically dead
