### ISSUE TITLE
Max count for GetUserTimeline from 200 to 3200

### ISSUE THREAD

**Issue by ChiefMateStarbuck** [bear/python-twitter#598]
I'm certain I have an idea as to how to increase the GetUserTimeline function from 200 to 3200 tweets.
Is there a specific reason as to why it hasn't increased as of yet?
If I can get a confirmation, I'll get started coding the solution up.

**Comment by morenoh149** [comment]
@ChiefMateStarbuck did you try it?

**Comment by jeremylow** [comment]
I just added [an example of how you'd do this using the GetUserTimeline](https://github.com/bear/python-twitter/commit/090ff41234c5629391b0615e9bce56bc9d76a8e8) function and the max_id parameter. 

That function only returns 200 tweets per call, so without writing the recursion or loop into the API client and potentially changing the function signature, I think the best way to go about it is to wrap the call in a loop progressively getting earlier and earlier tweets.
