### ISSUE TITLE
twitter.error.TwitterError: {'code': 44, 'message': 'attachment_url parameter is invalid.'}] #597

### ISSUE THREAD

**Issue by hsmatis** [bear/python-twitter#609]
This issue was closed.  However, I am getting the same problem and whatever I try gives me a 44 error.

I used the line
url= "https://www.google.com"
`twitter.error.TwitterError: [{'code': 44, 'message': 'attachment_url parameter is invalid.'}]`
I have tried many other urls and they all fail with the save error. Can anyone give me a url that actually works?

**Comment by jeremylow** [comment]
As mentioned here (https://github.com/bear/python-twitter/issues/597#issuecomment-442125539), the link needs to be a full tweet URL, so something like `https://twitter.com/ryanjjvance/status/1103372254161850368` will work.

**Comment by hsmatis** [comment]
You are correct that works. I read the documentation many times and did not understand that the only  link that only worked was a Twitter one.  I don't understand why they don't allow a normal HTML link.  My problem is  that the link that I want to include in the link takes about 75 characters and therefore takes up too much space.  I think the only solution is to find a service that shortens it.  To do that, I will need to automate the process.  This thread can be closed.
