### ISSUE TITLE
API's tweet_mode should default to extended, not truncated

### ISSUE THREAD

**Issue by davidmanheim** [bear/python-twitter#616]
It seems problematic to have the default behavior be **_not_** to get the full tweet text. Can this be changed?

(It was personally very frustrating to have done large amounts of work and find I needed to re-do everything to get the data. I'm sure there are backwards compatibility questions, but they should be minor.)

**Comment by jeremylow** [comment]
Yeah, that's a good call. The change was made long enough ago that most users should have migrated. Lands in https://github.com/bear/python-twitter/commit/d06a698773f5b8e520f8be954c83b2ec2ed13c8a
