### ISSUE TITLE
Need to obtain specific info from api.VerifyCredentials()

### ISSUE THREAD

**Issue by adrielav2** [bear/python-twitter#617]
The problem is that I need to get specific info from the user that logs in with my app, so when using VerifyCredentials I am trying to get for example his username, but I can't get specific info because it returns an user.Twitter and I need it as a dictionary or JSON, is there anyway around this? I am new at programming, sorry if it is kind of dumb.

**Comment by jeremylow** [comment]
Not dumb! You want either `user.screen_name` or `user._json['screen_name']`
