### ISSUE TITLE
Bad Link in Wiki

### ISSUE THREAD

**Issue by HEHenson** [bear/python-twitter#621]
This is similar to (Wiki points to wrong url #470)

If I click on the documentation in the wiki
the last release API documentation at: http://dev.twitter.com/doc 

"I get sorry that page doesn't exist"

This is June 17 in the evening

**Comment by andypiper** [comment]
Fixed all of the wiki links for the current version of the Twitter developer docs now.

**Comment by jeremylow** [comment]
Thank you @andypiper !
