### ISSUE TITLE
Tons of errors when running script for the first time.

### ISSUE THREAD

**Issue by Flipp3rrr** [bear/python-twitter#632]
# Problem
When I tried using this library for my Twitter application I immediately ran into problems; tons of errors. I have put the code and error log below.

# Code
```py
import twitter

api = twitter.Api(consumer_key=["NO U"],
                  consumer_secret=["NO U"],
                  access_token_key=["NO U"],
                  access_token_secret=["NO U"])

statuses = api.GetUserTimeline(screen_name="Flipp3rrr")
print([s.text for s in statuses])
```
NB: In the real script "NO U" is replaced with the token.

# Error log
https://pastebin.com/RHTfT7Z5

**Comment by jeremylow** [comment]
Are you putting the keys/tokens in a list []? They should be the strings like here https://github.com/bear/python-twitter/blob/master/examples/view_friends.py

**Comment by Flipp3rrr** [comment]
@jeremylow I used it like this:
```py
api = twitter.Api(consumer_key=["asdfasdf123"],
                  consumer_secret=["asdfasdf123"],
                  access_token_key=["asdfasdf123"],
                  access_token_secret=["asdfasdf123"])
```
Is this incorrect?

**Comment by Talvalin** [comment]
Based on the example given, yes that is incorrect. Try this?
(I used single quotes for consistency with the example code)

```
api = twitter.Api(consumer_key='asdfasdf123',
                  consumer_secret='asdfasdf123',
                  access_token_key='asdfasdf123',
                  access_token_secret='asdfasdf123')
```

**Comment by jeremylow** [comment]
Yeah, that's how it should be run.
