### ISSUE TITLE
GetListMembers returning only 100 users

### ISSUE THREAD

**Issue by matinas** [bear/python-twitter#661]
The GetListMembers call is returning only 100 members (default value for the GetListMembersPaged), because for some reason, that last call always returns the same value for `next_cursor `and `previous_cursor`, so the comparison `next_cursor == previous_cursor` is being always true, thus making the loop to break and return only the first page.

Don't know if it's due to a Twitter API change or something, but according to the latest docs in the Twitter API the only way to check whether we have reached the bottom of the list is by comparing next_cursor to 0:

> "You will know that you have requested the last available page of results when the API responds with a next_cursor = 0"

My actual call is: `auth.api.GetListMembers(None,slug,user,None,False,False)`

**Comment by matinas** [comment]
Just in case it helps, for now I solved the issue by replacing:

`if next_cursor == 0 or next_cursor == previous_cursor:`

with:

`if next_cursor == 0:`

**Comment by palewire** [comment]
I am getting this bug again in version 3.5
