### ISSUE TITLE
twitter.error.TwitterError: File size exceeds 5242880 bytes

### ISSUE THREAD

**Issue by reisenmachtfreude** [bear/python-twitter#662]
According to Twitter API there should be up to 15MB uploads possible (e.g. gif file)
Using python twitter API the limit seems to be much lower, which I don't understand:

twitter.error.TwitterError: File size exceeds 5242880 bytes.

**Comment by reisenmachtfreude** [comment]
probably the API thinks I'm uploading an image (limit is 5 MB) instead of gif. 
Code:
 `status = api.PostUpdate(message,media=feedEntry['thumb'])`

**Comment by Bracciata** [comment]
I am looking into this now and beginning to assume that the issue is we are using a dated link when posting a gif. I will update you with solution!

**Comment by Bracciata** [comment]
I am adding a merge request for the logic to fix this and I will link you to it when I am complete.
