### ISSUE TITLE
GetFriends() rate limiting in 1.1

### ISSUE THREAD

**Issue by bellmast** [bear/python-twitter#71]
With the change in how rate limiting works, is there any way to pull a user's entire friendlist if it's a very large list?

e.g.
friendz = api.GetFriends(screen_name='podcast411')

will throw "[{u'message': u'Rate limit exceeded', u'code': 88}]"
without resolving (i.e., friendz will remain undefined)

Can we page through the list from GetFriends(), add (e.g. the .names) to a dictionary or list, and tell Python to sleep for 15 minutes when we hit the rate limit?  

Some of this obviously needs to be handled in the app's/user's code, but it feels like something is missing from the Python Twitter def (or that I'm missing something).

**Comment by jeremylow** [comment]
Closing with #299
