### ISSUE TITLE
Streaming API

### ISSUE THREAD

**Issue by denisvolokh** [bear/python-twitter#74]
Hi,

Will your library support Twitter Streaming API?

**Comment by ambrosechua** [comment]
+1

**Comment by radlws** [comment]
I think its a must. A good place to start is to see what other python twitter libraries are doing:

https://dev.twitter.com/overview/api/twitter-libraries

**Comment by jeremylow** [comment]
lol, OK, so I'm going to close this issue, because 1. streaming support is pretty good, and 2. Twitter is doing away with the UserStream and that's going to be a whole other thing.
