### ISSUE TITLE
twitter_test.py failures

### ISSUE THREAD

**Issue by jarobins** [bear/python-twitter#94]
Need to address the failures with the twitter_test script and fix/remove them. 

On my Windows 7 machine with python 2.7.3 installed I get 17 test failed.

All these failures stem from having an Invalid or expired token. (perhaps I need a lesson in running this script?)

Anybody else get the same?

**Comment by buglessdr** [comment]
Bump - same issue

**Comment by gwenzek** [comment]
I tried on Ubuntu 14, with python 2.7 and I failed the last 16 tests with an authentication error:

    TwitterError: [{u'message': u'Invalid or expired token.', u'code': 89}]

**Comment by jonathan-s** [comment]
@bear this issue could be closed as well. Since the user is required to provide their own tokens from now on.
